### ISSUE TITLE
Datum wird falsch ausgegeben

### ISSUE THREAD

**Issue by Philipp1978** [terminal42/contao-leads#100]
Hallo zusammen,

ich habe am Wochenende das OptIn-Verfahren über Contao Leads eingebaut und bin begeistert. Zusammen mit dem Notification-Center sind die Möglichkeiten nahezu unbegrenzt. Wirklich großartig.

An einer Stelle habe ich ein seltsames Verhalten festgestellt. Ich frage ein Geburtsdatum ab und speichere es in den Leads ab. Das Geburtsdatum wird dort korrekt abgespeichert und im Contao Backend auch korrekt wiedergegeben. Wenn ich dieses Datum allerdings in einer Email verwende (mittels ##leads_Geburtsdatum##) wird daraus eine Nummer gemacht. Aus 01.01.2001 wurde 978303600.

Ist das ein Bug oder habe ich irgendwo einen Einstellungsfehler drin?

Viele Grüße
Philipp

**Comment by netzarbeiter** [comment]
Bei der Zahl handelt es sich um einen Timestamp, diesen kannst du mit der Hilfe folgendes Insert-Tags formatieren: 

`{{formatted_datetime::##leads_Geburtsdatum##::d.m.Y}}`
