### ISSUE TITLE
Problem beim Export von Checkboxen mit nur einer Auswahlmöglichkeit

### ISSUE THREAD

**Issue by cmartin6** [terminal42/contao-leads#101]
Ich habe eine Formularfeld Checkbox-Menü mit dem Feldnamen "gewinnspiel" und der Feldbezeichnung "Gewinnspielteilnahme" mit nur einer Option (Wert "yes", Bezeichnung "Ja, ich will teilnehmen ...").

Ich habe auf "individueller Export" umgestellt und die Felder entsprechend ausgefüllt. "Wert" --> "Nur den Wert", "Format" --> "Rohdaten" ... alle Felder werden korrekt exportiert, aber bei der o.g. Checkbox mit nur einer Option wird immer "nein" in der Spalte angezeigt.

nein

Wenn ich bei "Wert" umstelle auf "Bezeichnung und Wert" dann wird es auch falsch ausgegeben:

"Gewinnspiel [nein]"

Andere Checkbox-Felder mit mehr als einer Option geben den Wert korrekt aus!

**Comment by aschempp** [comment]
bitte keine Duplikate anlegen: https://github.com/terminal42/contao-leads/issues/59
