### ISSUE TITLE
Abandoned packages

### ISSUE THREAD

**Issue by mathContao** [terminal42/contao-leads#103]
Beim Aktualisieren meldet der Contao Manager, dass Leads Packages nutzt, die anscheinend nicht mehr auf dem aktuellen Stand sind.

Siehe Screenshot:

![grafik](https://user-images.githubusercontent.com/1645099/102531561-cb064f00-40a2-11eb-85e7-2b0a1972ca08.png)

**Comment by Toflar** [comment]
Warum sollte dafür Leads zuständig sein? Das sind separate Zeilen die miteinander überhaupt nichts zu tun haben.
Warum ein Paket installiert wurde, sagt dir ein `composer why`.
In diesem Fall sind die Pakete von Contao oder von transitiven Abhängigkeiten, über die wir keine Kontrolle haben - die Warnung kannst du also als reiner User ignorieren :)
