### ISSUE TITLE
Veralteter MultiColumnWizard

### ISSUE THREAD

**Issue by eki89** [terminal42/contao-leads#105]
Hallo zusammen. :)

Das Leads Bundle setzt noch immer auf den alten MultiColumnWizard, welcher in neuen Contao Versionen nicht mehr zuverlässig funktioniert. Gibt es einen Grund, weshalb nicht auf das neue Bundle (3.4) gesetzt wird?

Sämtliche Erweiterung, die ebenfalls den MultiColumnWizard benötigen, funktionieren aus diesem Grund nicht mehr richtig, sodass diese nicht in Kombination mit dem Leads Bundle genutzt werden können.

**Comment by fritzmg** [comment]
> Das Leads Bundle setzt noch immer auf den alten MultiColumnWizard, welcher in neuen Contao Versionen nicht mehr zuverlässig funktioniert. Gibt es einen Grund, weshalb nicht auf das neue Bundle (3.4) gesetzt wird?

Leads is still compatible with Contao 3 and thus cannot directly require `terminal42/contao-multicolumnwizard-bundle`.

> Sämtliche Erweiterung, die ebenfalls den MultiColumnWizard benötigen, funktionieren aus diesem Grund nicht mehr richtig, sodass diese nicht in Kombination mit dem Leads Bundle genutzt werden können.

Why would that be the case? `terminal42/contao-multicolumnwizard-bundle` replaces `terminal42/contao-multicolumnwizard`. So if you install any extension that requires `terminal42/contao-multicolumnwizard-bundle`, `terminal42/contao-multicolumnwizard` will automatically be replaced with `terminal42/contao-multicolumnwizard-bundle` for you. If you have any problems with this process, please post on the community forums.

**Comment by eki89** [comment]
Hallo fritzmg,
vielen Dank für deine Nachricht. Du hast absolut recht, allerdings habe ich unter bestimmten Bedingungen noch immer ein Problem, dass ich im Moment leider nicht reproduzieren kann. Ich prüfe den Sachverhalt nochmal. Ich schließe das Issue wieder, da meine Behauptung tatsächlich in dieser Form nicht zutrifft und damit falsch ist. Entschuldige den Fehlalarm.
