### ISSUE TITLE
XLS/XLSX: Special characters like () " are converted in field title and Text area content 

### ISSUE THREAD

**Issue by woodyc79** [terminal42/contao-leads#107]
Hello!

Characters like ( ) and " are encoded in the XLS/XLSX
Line breaks from the text areas are also gone in the cells.
 
![image](https://user-images.githubusercontent.com/1710712/106930064-67e58000-6715-11eb-99ba-a703a8d4b1e1.png)

Kind regards
Chris

**Comment by aschempp** [comment]
this is no longer the case in the upcoming version 3.
