### ISSUE TITLE
Support editing of stored leads data

### ISSUE THREAD

**Issue by cliffparnitzky** [terminal42/contao-leads#11]
It would be fine, if the stored leads data could be editied in backend.

Maybe deleting is also a nice option.

**Comment by MacKP** [comment]
+1

**Comment by zonky2** [comment]
+1

**Comment by zonky2** [comment]
+1

**Comment by aschempp** [comment]
I'm not a fan of this idea. Leads is supposed to capture what users entered in a form for further processing (e.g. CRM application, using the flexible export options). 

If you want data store and editing, you should use an extension that is made for this (e.g. MetaModels with frontend editing, maybe fModule etc. )

**Comment by madmaharaja** [comment]
In an ideal world, users would only enter error-free data into a form which is still accurate a week later. However, in reality this is not the case. Plus, from my experience sometimes you as the webmaster will update the form (e.g. add additional fields) and it would be great if it was possible to also add this information to entries that had been entered in the past. Last but not least it would be handy if one could add own annotations as a webmaster and manage the information all in one place (Leads). Therefore I'm also in support of this request: +1

**Comment by Schmidty2** [comment]
+1

**Comment by NinaG** [comment]
I'm urgently in need of this feature for contao-leads and would be willing to pay for it. Maybe you could release it as addon for contao-leads? Please contact me. Thank you :)

**Comment by kroerig** [comment]
I also think there needs be a possibilty to edit the records before you transfer them to other systems.

In my case, I know that Android/ iOS autocorrections miscorrected some values and I have to fix them as soon as I see them because later nobody will take care of this.

**Comment by aschempp** [comment]
As I explained, in my opinion this conflicts with the idea of this extension. If you need this feature, feel free to use or create another extension that does that.

**Comment by fritzmg** [comment]
I also think that this should be integrated in Leads as this extension is the best solution for capturing form data (without manually creating a DCA) - and the simple fact of the matter is that users also want to sometimes edit this data for whatever reason.

**Comment by zonky2** [comment]
If you want to implement this for the backend, you would have to create a DCA input mask dynamically from the data. I don't think that's trivial. The input type would have to be taken from the form, as it is not saved with it. It might be easier to create a way to load a data set back into the original form - possibly in a modal window in the BE.

**Comment by Toflar** [comment]
> As I explained, in my opinion this conflicts with the idea of this extension. If you need this feature, feel free to use or create another extension that does that.
