### ISSUE TITLE
Is it possible to use insert tag flags with simple tokens?

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-leads#112]
I like to **trim** a value and wonder if I somehow can use an insert tag flag or something else to trim a value/"simple token"

https://docs.contao.org/manual/de/artikelverwaltung/insert-tags/#insert-tag-flags

Someone has an idea how to achieve this?

**Comment by aschempp** [comment]
I don't think that's related to this extension, please use the Slack channel or Community Forums.

**Comment by Aybee** [comment]
Ok, thank you.
