### ISSUE TITLE
Custom export with Simple Tokens - Column field?

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-leads#113]
Anyone knows what this field "Column" is good for? I put in some numbers, but can't see any result.

![Bildschirmfoto am 2021-04-13 um 22 47 44](https://user-images.githubusercontent.com/1143013/114460162-b44faf00-9be1-11eb-838a-5a5a6d81ebc1.png)

**Comment by aschempp** [comment]
I think the idea is that you might skip some columns to match your excel template

**Comment by Aybee** [comment]
Mmh, ok. So with export without template is has no effects? I was wondering because this field is mandatory.
