### ISSUE TITLE
How to export with a template?

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-leads#114]
With export as xls(x) you can use a template. Does someone know how this works?

![Bildschirmfoto am 2021-04-13 um 22 56 05](https://user-images.githubusercontent.com/1143013/114461983-bbc38800-9be2-11eb-8a22-88f03a01186e.png)

**Comment by aschempp** [comment]
Not sure what's unclear? You select a template and the data is appended to the respective sheet at the respective line.

**Comment by Aybee** [comment]
An example would be nice. What's the benefit of this way? Do I have to use placeholders within the template?

I was thinking about that maybe this is a way to get the ##created## variable into the export via PHP which does not work with other export functionalities at the moment.

**Comment by aschempp** [comment]
This is about an excel template file (an excel file that already has content), not a PHP template.

**Comment by Aybee** [comment]
Ok, thank you.
