### ISSUE TITLE
Symbole ausblenden funktioniert nur teilweise

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-leads#123]
Hallo,

zuerst die technischen Infos:
Contao 4.9.27
Leads 1.4.21
PHP 7.4.28
Provider All-Inkl
Es läuft alles fehlerfrei.

Ich möchte die Symbole bei Leads ausblenden.
Dazu habe ich eine Datei erstellt:

contao/dca/tl_lead.php
// Leads Menüpunkte für BE-User ausblenden
if (!BackendUser::getInstance()->isAdmin)
{
    // Symbole ausblenden
    unset ($GLOBALS['TL_DCA']['tl_lead']['list']['operations']['delete']);
    unset ($GLOBALS['TL_DCA']['tl_lead']['list']['operations']['show']);
    unset ($GLOBALS['TL_DCA']['tl_lead']['list']['operations']['data']);
    unset ($GLOBALS['TL_DCA']['tl_lead']['list']['operations']['notification']);
}

Hier greifen die ersten drei Anweisungen, aber die vierte Anweisung für die Notification greift nicht, das Symbol wird weiter angezeigt.

Wenn ich die Anweisung für die Noification in die Datei dcaconfig.php schreibe, wird das Notification-Symbol ausgeblendet, aber der Weg über die dcaconfig.php soll ja ncht mehr verwendet werden:

system/config/dcaconfig.php
// Leads Menüpunkte für BE-User ausblenden
if (!BackendUser::getInstance()->isAdmin)
{
    // Symbol ausblenden
    unset ($GLOBALS['TL_DCA']['tl_lead']['list']['operations']['notification']);
}

Was muss ich in contao/dca/tl_lead.php schreiben, damit das Notification-Symbol ausgeblendet wird?
Oder ist das ein Bug?

**Comment by cliffparnitzky** [comment]
Der Button ist via Callback hinzufgefügt. Um den auszublenden, muss der Callback überschrieben werden.

Btw. Sowas ist im Forum oder im Slack immer besser platziert.

**Comment by Schmidty2** [comment]
Hallo,
ich hatte das bereits vor einiger Zeit [im Forum angefragt](https://community.contao.org/de/showthread.php?74134-Leads-Symbole-im-Backend-ausblenden), aber keine Rückmeldung bekommen.

Wie muss ich einen Callback überschreiben?
Ich bin kein Programmierer bzw. Entwickler und benötige eine Detaillierte Anleitung dafür, Danke.

**Comment by cliffparnitzky** [comment]
Uff, das ist ja mehr als ein Jahr her.

Hab mal meine Antwort ins Forum geschrieben. Vlt. erstellt dir dort jemand eine deteillierte Anleitung. Ansonsten @terminal42 oder jmd. andere Entwickler beauftragen.
