### ISSUE TITLE
Add a listing/details frontend module

### ISSUE THREAD

**Issue by cliffparnitzky** [terminal42/contao-leads#13]
Because we have 2 database tables, the core listing module could not be used to display leads and lead data in frontend. Mmoreover this will be very hard to configure for non tech users.

A special listing module with som filters an da detail view would be fine.

**Comment by aschempp** [comment]
In my opinion, leads are not supposed to be shown on the website. What's your use case?

**Comment by Toflar** [comment]
In my opinion, there are valid use cases. I'll assign it to a future milestone, though. I would like to have it rewritten using a model class that joins the data table automatically anyway so a listing module should be piece of cake afterwards. Feel free to add PR's :)

**Comment by rflx** [comment]
+1

**Comment by fritzmg** [comment]
:+1:

**Comment by overheaddesign** [comment]
Ich hab gleich noch etwas hinzuzufügen.
Auflistung wo man den Datensatz editieren kann. ganz wichtig.

**Comment by cliffparnitzky** [comment]
Also Editieren sollte nicht auch noch rein ... irgendwo sollte man entscheiden, ob man MetaModels nimmt ... oder nur simpel speichert ... das wäre, so denke ich, an dieser Stelle.

**Comment by fritzmg** [comment]
Naja, der Wunsch zum editieren hat ja nicht direkt etwas mit MetaModels zu tun. Ich kann diesen Feature Request durchaus nachvollziehen, vor allem da contao-leads als teilweiser Ersatz für EFG gesehen wird.

**Comment by cliffparnitzky** [comment]
Ja kann ich auch. ABER, wenn man bedenkt, was die Entwicklung kosten würden, wäre es durchaus sinnvoller die Zeit in FE Editing von MM zu verbraten. Auch um die Ressourcen besser zu bündeln

Sind ja alles so [efg] Ablösungen - davon können wir ja wieder zig unfertige haben. Oder aber wir konzentrieren uns als Community auf je 1 richtige. Über einen Art Matrix sollte jedem Anwender dann z.B. ersichtlich sein, welche Extension bei welchem Anwendungsfall einzusetzen sind.

**Comment by fritzmg** [comment]
Ja verstehe ich natürlich.

Bei der Lösung mit MetaModels meinst du, nicht contao-leads zum abspeichern der Daten zu benutzen, sondern die Core Funktionalität und direkt in eine `mm_` Tabelle speichern, oder?

**Comment by cliffparnitzky** [comment]
Ja richtig.

Die Matrix war vor einiger Zeit in einer Arbeitsgruppe mal angedacht. Mit der AG sollte ermittelt werden, was vom [efg] als alternative Erweiterung noch fehlt. Außerdem sollte diese Matrix für verschieden Anwendungsfälle erstellt werden. Sie soll halt klar machen, dass man bis zu einen Umfang X mit Leads gut klar kommt und ab Y auf MM wechseln sollte. Vlt. wird diese Matriy ja noch mal entworfen.

**Comment by cliffparnitzky** [comment]
Hier für das Listing Modul sehe ich die einfache Erfassung von Formulardaten und dann die Ausgabe als Liste, z.B.  eine Event-Buchung, etc. Ggf. Bearbeitung im Sinne der Korrektur müsste ein Admin im Backend machen.

Eine komplette User-Interaktion mit nachträglichen Bearbeiten, ggf. Löschen ist davon noch viel weiter entfernt.

**Comment by hella-schu** [comment]
+

**Comment by Toflar** [comment]
Ich schliesse das Ticket, weil wir uns einig sind, dass leads niemals über Frontend-Funktionalität verfügen wird. Dafür wurde es nicht gebaut. Wenn jemand eine Extension bauen will, die auf leads aufsetzt, soll er das tun.
