### ISSUE TITLE
Automatic deletion of stored data?

### ISSUE THREAD

**Issue by con2net** [terminal42/contao-leads#130]
In order not to keep stored lead data longer than necessary, an option to automatically delete data after x days would be helpful. Is this already provided for in some way or do you think it doesn't make sense at this point?

I could also delete it directly in the database, but an option directly in Contao would be more appropriate.

**Comment by fritzmg** [comment]
This is already implemented in the current `develop` branch: https://github.com/terminal42/contao-leads/pull/61

**Comment by con2net** [comment]
Tx, Fritz!
