### ISSUE TITLE
Export-Funktion nicht sichtbar

### ISSUE THREAD

**Issue by BlackThunder22** [terminal42/contao-leads#131]
Hallo zusammen,

ich habe Leads und phpoffice/phpspreadsheet installiert, sehe auch die Anfragen, welche über das Kontaktformular eingereicht wurden, aber keine Möglichkeit die Daten zu exportieren? Was mache ich falsch?

Contao Manager 1.6.0
Contao 4.13.10
phpoffice/phpspreadsheet 1.25.2
Leads: 1.4.33

**Comment by Kahmoon** [comment]
Sowas gehört eher ins contao Forum https://community.contao.org/de/forumdisplay.php?10-Support-f%C3%BCr-Contao-Erweiterungen 

Ist ja kein direkter Fehler.

Hast du eine Konfiguration für einen Export erstellt?
![SCR-20221003-jxp](https://user-images.githubusercontent.com/6390770/193575441-a0e0e584-2e57-4a31-ad06-efd5f252bd6e.png)

**Comment by BlackThunder22** [comment]
> Sowas gehört eher ins Contao Forum https://community.contao.org/de/forumdisplay.php?10-Support-f%C3%BCr-Contao-Erweiterungen
> 
> Ist ja kein direkter Fehler sondern vermutlich eine falsche oder nicht vorhandene Konfiguration. Hast du einen Export erstellt?
> 
> ![SCR-20221003-jxp](https://user-images.githubusercontent.com/6390770/193575441-a0e0e584-2e57-4a31-ad06-efd5f252bd6e.png) <img alt="Bildschirmfoto 2022-10-03 um 14 23 57" width="379" src="https://user-images.githubusercontent.com/6390770/193575798-90187f2d-d3a6-44ca-866f-6ea1782d9719.png">

Danke, hat geholfen! Da wäre ich nie drauf gekommen.
