### ISSUE TITLE
Berechtigungen auf Export-Konfigurationen

### ISSUE THREAD

**Issue by kroerig** [terminal42/contao-leads#135]
Hallo,
ich vermissen folgende Möglichkeit:
- Verschiedenen Benutzern/Gruppen auf unterschiedliche Export-Konfigurationen geben,

Hintergrund: Ich muss (in meinem Fall) Daten erfassen, die in den Bereich "besonders schützenswert" fallen. Ein Report mit diesen Daten darf nur von bestimmten Personen gemacht werden. Alle anderen sollten aber trotzdem noch die Grunddaten exportieren können.

Dazu habe ich ich zwei Konfigurationen angelegt. Aber ich finde keine Möglichkeit Zugriffsrechte zu setzen.

**Comment by aschempp** [comment]
Sobald jemand Zugriff auf die Lead-Daten hat, kann er/sie doch sowieso alles sehen? Auch die "besonders schützenswerten" Daten sind immer ersichtlich?

**Comment by kroerig** [comment]
hm. Dann müsste Berechtigungen auf die Felder setzen können.

**Comment by aschempp** [comment]
Leads weiss nicht welche Felder du hast, daher kann Contao auch keine Berechtigungen dazu anbieten. 

Ich denke das ist kein "Standard"-Fall für Leads. Ich würde dir empfehlen für den Fall ein eigenes Backend-Modul dafür zu entwickeln/entwickeln zu lassen, die Daten für genau deinen Fall zu speichern ist da sicher zielführender.
