### ISSUE TITLE
Leads und Haste ^5.0

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-leads#136]
Hallo,
Leads hat Contao-Haste auf Version 4 ("codefog/contao-haste": "^4.10.0) fixiert und verhindert deshalb ein Update einiger Erweiterungen, die bereits Haste ^5.0 fordern (In meiner Installation Leads und markocupic/calendar-event-booking-bundle).
Kann Haste ^5.0 für Leads freigegeben werden oder ist bereits ein Update in Planung?

PHP 8.1.16
Contao 4.13.16
ContaoManager 1.6.3

**Comment by fritzmg** [comment]
https://github.com/terminal42/contao-leads/pull/133
