### ISSUE TITLE
Not able add packet lead to contao, trider different configurations but get always conflicts

### ISSUE THREAD

**Issue by pgunzelmann** [terminal42/contao-leads#137]
$ /usr/bin/php8.1-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /homepages/15/d16305443/htdocs/cms/web/contao-manager.phar.php composer require terminal42/contao-leads --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Using version ^1.4 for terminal42/contao-leads
/homepages/15/d16305443/htdocs/cms/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

> Resolving dependencies using Composer Cloud v3.5.1

[6.6MiB/0.17s] Loading composer repositories with package information
[66.5MiB/8.57s] Updating dependencies
[83.4MiB/8.91s] Your requirements could not be resolved to an installable set of packages.
[83.4MiB/8.91s] 
  Problem 1
    - terminal42/contao-leads[1.4.0, ..., 1.4.33] require codefog/contao-haste ^4.10.0 -> found codefog/contao-haste[4.10.0, ..., 4.25.25] but these were not loaded, likely because it conflicts with another require.
    - terminal42/contao-leads[1.4.7, ..., 1.4.20] require php ^5.3.2 || ^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.
    - Root composer.json requires terminal42/contao-leads ^1.4 -> satisfiable by terminal42/contao-leads[1.4.0, ..., 1.4.33].

[83.4MiB/8.92s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[37.5MiB/8.94s] Memory usage: 37.46MB (peak: 189.61MB), time: 8.95s.
[37.5MiB/8.94s] Finished Composer Cloud resolving.

# Cloud Job ID y05zSmNVSlUl63sqrMMob6sD3PVkelp9mXUSX48FXDCC8AFo8yEQJCpaqYqn4JJ6Z5chMbdyh failed

**Comment by pgunzelmann** [comment]
May compare requirement chek with Notification Center it could be installed on the conditons of the core

**Comment by pgunzelmann** [comment]
it seems my packets had not ben upe to date

**Comment by fritzmg** [comment]
You need to require `terminal42/notification_center: ^1.6` (in addition to leads) and then run a full `composer update`.

**Comment by pgunzelmann** [comment]
Thank you for your answer
Notification Center is installed with 1.7
on which place i can run a full composer update

**Comment by pgunzelmann** [comment]
coud find the update at the contao manager, but unfortunately no sucess.

**Comment by fritzmg** [comment]
Post your composer.json

**Comment by pgunzelmann** [comment]
{
    "type": "project",
    "require": {
        "codefog/contao-haste": "^5.1",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "4.13.*",
        "terminal42/contao-mp_forms": "^5.0",
        "terminal42/notification_center": "^1.7"
    },
    "extra": {
        "public-dir": "web",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}

**Comment by pgunzelmann** [comment]
I set up contao newly, and tried differend versions (also 5.x) deleted all and started with a nwe installation (including deleding database) unfornately all tries i did always differendt problems occured. At contao manager if i open info of leads no conflicts are displayed

php

^7.0 || ^8.0

Contao Core

^3.5.1 || ^4.1
Details

contao-community-alliance/composer-plugin

^2.4.0 || 3.*
Details

Contao Haste

^4.10.0
Details

menatwork/contao-multicolumnwizard

~3.2
Details

**Comment by pgunzelmann** [comment]
A Try with Contao 5.1 even more problems ouccure:

$ /usr/bin/php8.1-cli -q -dmax_execution_time=0 -dmemory_limit=-1 -ddisplay_errors=0 -ddisplay_startup_errors=0 -derror_reporting=0 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /homepages/15/d16305443/htdocs/cms/web/contao-manager.phar.php composer require terminal42/contao-leads --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.4 for terminal42/contao-leads
/homepages/15/d16305443/htdocs/cms/composer.json has been updated

# Process terminated with exit code 0
# Result: OK


> Resolving dependencies using Composer Cloud v3.5.1

[6.7MiB/0.18s] Loading composer repositories with package information
[73.2MiB/8.04s] Updating dependencies
[145.0MiB/8.88s] Your requirements could not be resolved to an installable set of packages.
[145.0MiB/8.89s] 
  Problem 1
    - terminal42/contao-leads[1.4.3, ..., 1.4.33] require contao/core-bundle ^3.5.1 || ^4.1 -> satisfiable by contao/core-bundle[4.1.0, ..., 4.13.16], contao/core[3.5.1, ..., 3.5.40].
    - terminal42/contao-leads[1.4.0, ..., 1.4.2] require contao/core-bundle ^3.5 || ^4.1 -> satisfiable by contao/core-bundle[4.1.0, ..., 4.13.16], contao/core[3.5.0, ..., 3.5.40].
    - Only one of these can be installed: contao/core[2.10.0, ..., 2.11.17, 3.0.0, ..., 3.5.40], contao/core-bundle[4.1.0, ..., 4.13.16, 5.1.0]. contao/core replaces contao/core-bundle and thus cannot coexist with it.
    - contao/core-bundle 4.4.0 requires terminal42/header-replay-bundle ^1.0 -> satisfiable by terminal42/header-replay-bundle[1.0.0, ..., 1.5.3].
    - contao/core[3.5.0, ..., 3.5.40] require contao-community-alliance/composer-plugin ~2.0 -> satisfiable by contao-community-alliance/composer-plugin[2.0.0, ..., 2.4.3].
    - contao/manager-bundle 5.1.0 requires contao/core-bundle 5.1.0 -> satisfiable by contao/core-bundle[5.1.0].
    **- terminal42/contao-leads[1.4.7, ..., 1.4.20] require php ^5.3.2 || ^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.**
    - contao-community-alliance/composer-plugin[2.0.0, ..., 2.3.3] require composer-plugin-api 1.0.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - terminal42/header-replay-bundle[1.0.0, ..., 1.4.4] require php >=5.6,<8 -> your php version (8.1.16.0) does not satisfy that requirement.
    - terminal42/header-replay-bundle[1.5.0, ..., 1.5.3] require php ^5.6 | ^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.
    - contao-community-alliance/composer-plugin[2.3.4, ..., 2.4.3] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - contao/core-bundle[4.4.1, ..., 4.4.17] require php ^5.6|^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.
    - contao/core-bundle[4.4.18, ..., 4.4.57] require php ^5.6 || ^7.0 -> your php version (8.1.16.0) does not satisfy that requirement.
    - contao/core-bundle[4.5.0, ..., 4.8.8] require php ^7.1 -> your php version (8.1.16.0) does not satisfy that requirement.
    - contao/core-bundle[4.9.0, ..., 4.10.4] require php ^7.2 -> your php version (8.1.16.0) does not satisfy that requirement.
    - Root composer.json requires contao/manager-bundle 5.1.* -> satisfiable by contao/manager-bundle[5.1.0].
    - Root composer.json requires terminal42/contao-leads ^1.4 -> satisfiable by terminal42/contao-leads[1.4.0, ..., 1.4.33].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
[145.0MiB/8.89s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[42.7MiB/8.97s] Memory usage: 42.69MB (peak: 192.91MB), time: 8.98s.
[42.7MiB/8.97s] Finished Composer Cloud resolving.


# Cloud Job ID ITfdlUQb7n0J89wVxTCGZ1MoaZzshIIGLlM7nojgo3TCxop86tpCgVWKG84d5fy0dkxDx1nIxyNYP failed

The composer.json has following content:

{
    "type": "project",
    "require": {
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "5.1.*"
    },
    "extra": {
        "public-dir": "web",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}

**Comment by pgunzelmann** [comment]
At https://github.com/terminal42/contao-notification_center
i found a good overview tabel about compatibility, may it would be good to add an according table to leads also

**Comment by fritzmg** [comment]
You cannot install `terminal42/contao-leads` due to the following dependencies in your `composer.json`:

* `"codefog/contao-haste": "^5.1"`
* `"terminal42/contao-mp_forms": "^5.0"`
* `"terminal42/notification_center": "^1.7"`

If you don't use `codefog/contao-haste` in your own code then you can remove that. If you do not need `terminal42/contao-mp_forms` in the newest version you can also allow version 4 to be installed. If you don't need `terminal42/notification_center` in the newest version you can also allow version 1.6 to be installed.

e.g.:

```json
{
    "type": "project",
    "require": {
        "contao/conflicts": "@dev",
        "contao/manager-bundle": "4.13.",
        "terminal42/contao-mp_forms": "^4.0 || ^5.0",
        "terminal42/notification_center": "^1.6",
        "terminal42/contao-leads": "^1.4"
    },
    "extra": {
        "public-dir": "web",
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "@php vendor/bin/contao-setup"
        ]
    }
}
```

**Comment by pgunzelmann** [comment]
I installed Conao based on 4.13 now and everithyng run well now. Thanks for the lot of hints. I first tought the Cantao manager tells me which combinateion is possible, but not i kno not every combination shows the right base conditions and so i first assumed it will work with contao 5.1 . For my needs everithyng is fine now with 4.13. Thanks alot.

**Comment by fritzmg** [comment]
Only composer will be able to tell you that once you run the package update.

**Comment by pgunzelmann** [comment]
I could do first steps with leads now, unfortunately i can't find an example which sence subformulars have. 
 How depend subformular from mainformular ?
