### ISSUE TITLE
Add some missing translations

### ISSUE THREAD

**Issue by cliffparnitzky** [terminal42/contao-leads#14]
Some translations are missing (e.g. tooltip for button `data`)

**Comment by aschempp** [comment]
The translations are managed on Transifex (https://www.transifex.com/projects/p/notification_center/). I couldn't find a button `data` though. If the bug is in english, please reopen the ticket and add more details.

**Comment by aschempp** [comment]
I just noticed you're not talking about notification center ^^

**Comment by aschempp** [comment]
Added in f7d83856035b5708fb425a2a38fadea3dccbd548
