### ISSUE TITLE
Konfiguration mit Template zeigt "Invalid UTF-8 string" Fehler

### ISSUE THREAD

**Issue by LBeckX** [terminal42/contao-leads#140]
Wenn ein Template gewählt wurde, wird in der Übersicht "Konfiguration" folgender Fehler ausgegeben:

![image](https://user-images.githubusercontent.com/11272361/236140619-e2b73131-d99b-42b0-863a-e93bb49f31ce.png)

Wenn ich den String ausgeben lasse, wird das hier ausgegen:
`��f����H���^_template`

Habt Ihr eine Idee, an was das liegt?

Folgend die Datei, die als Template genutzt wird:
[Musterdatei.xls](https://github.com/terminal42/contao-leads/files/11395167/Musterdatei.xls)

**Comment by aschempp** [comment]
hast du in dem Formular eine Datei hochgeladen? ist das ev. eine File-UUID ?

**Comment by LBeckX** [comment]
@aschempp ich denke, dass es sich um eine File uuid handelt. Allerding nicht um eine Datei von einem Upload-Feld in dem Formular selber (gibt keine Möglichkeit des Uploads), sondern eben um die Template-Datei aus der Export-Konfiguration.
Denn diese Fehlermeldung kommt nur, wenn ich ein Template (Musterdatei.xls) auswähle.

**Comment by LBeckX** [comment]
@aschempp könntest Du mich hier unterstützen? Das wäre super 👍🏼

**Comment by LBeckX** [comment]
@aschempp den Fehler konnte ich beheben indem in in der Datei
`tl_lead_export` 
den Block 235 bis 241 folgendermaßen geändert habe

```php
'template' => [
            'exclude' => true,
            'filter' => false,
            'inputType' => 'fileTree',
            'eval' => ['filesOnly' => true, 'fieldType' => 'radio', 'mandatory' => true, 'tl_class' => 'clr'],
            'sql' => "binary(16) NULL"
],
```

**Comment by LBeckX** [comment]
https://github.com/terminal42/contao-leads/pull/143
