### ISSUE TITLE
Spalten überspringen funktioniert nicht mit ".xls" Format

### ISSUE THREAD

**Issue by LBeckX** [terminal42/contao-leads#141]
In der aktuellen Version *3.0* können in .xls keine Spalten übersprungen werden.
In der Version 1.4 hat dieses Feature funktioniert mit der selben Template-Datei.
Habt Ihr eine Idee an was das liegt?
Folgen die Template Datei, die genutzt wird:
[Musterdatei.xls](https://github.com/terminal42/contao-leads/files/11395173/Musterdatei.xls)

**Comment by aschempp** [comment]
kannst du einen Screenshot deiner Export-Konfiguration machen?

**Comment by LBeckX** [comment]
@aschempp leider aktuell nicht, da es zu dem Fehler kommt, welcher in diesem Ticket beschrieben ist:
https://github.com/terminal42/contao-leads/issues/140

**Comment by LBeckX** [comment]
@aschempp hab den Fehler behoben:
https://github.com/terminal42/contao-leads/pull/143
