### ISSUE TITLE
missing storage option for file uploads in Contao 5.1.6

### ISSUE THREAD

**Issue by Baloobear** [terminal42/contao-leads#142]
Hi,

I was wondering where I get the Information which files have been sent with a form and then I stumbled upon the missing option in the file upload form element to define if the data will be stored, like I have at other form fields.
Currently I'm using Contao 5.1.6 but I'm not sure if this is a generic problem with all 5.x or 5.1.x installations.

Hope this is just a minor issue and might be solvable with ease.

If you need any further information for debugging just let me know.

Thanks.
Dennis

**Comment by HoTodo** [comment]
Hello,

I want to second the request from @Baloobear (with Contao 5.1.6 and Leads 3.0.0 here)
I just stumbled over the same issue and can not make a connection between the uploaded file and the Lead record.
(I'll try to inject some Javascript into my form to rename the upload file in a recognizable way before submitting the form.)

Unfortunately I do not have any additional information other than: Baloobear is not the only one having this issue.

Anyways:
This is a great extension and it is really the missing piece for the whole save-your-form-data-to-database feature. Thank you for that.
