### ISSUE TITLE
stored value of hidden field only from linked main form

### ISSUE THREAD

**Issue by Baloobear** [terminal42/contao-leads#144]
Hi there,

I have two similar forms where I have also a hidden form field included. The field name is the same at both forms but the value is different. Unfortunately only the value of the linked main form is stored in the leads table but not the value from the sub-form, when submitted.

I think this might be a wrong behavior or am I wrong?

**Comment by aschempp** [comment]
That sounds strange. The hidden value is submitted in the front end form, right? Leads would only store what's submitted, not what's in another form. Can you check if the correct hidden value is visible in the source code before submitting the form?

**Comment by Baloobear** [comment]
Hi,

I'm sorry. This was my fault. It seems that I missed to set the correct form. All is fine now.
Thanks.
