### ISSUE TITLE
Multiple Checkbox Value displayed as serialized string in Export

### ISSUE THREAD

**Issue by LBeckX** [terminal42/contao-leads#147]
Hi together,
The checkbox menu gives me the data in the export as a serialized array.
Is there a way to output the values as a simple list?
Thanks in advance

Konfiguration:

![image](https://github.com/terminal42/contao-leads/assets/11272361/d6566727-9e64-4bbd-a95e-616ae0726a17)

**Comment by fritzmg** [comment]
Each lead is one row in the export, one column for each field. Thus multiple values need to be serialised.

**Comment by LBeckX** [comment]
Thank you for the quick answer.
Is there a simple way to modify the output or register a new value parser like "Rohdaten", "Ja/Nein", "Email", "Datum/Zeit", etc.?

**Comment by aschempp** [comment]
they are not supposed to be serialized… can you show an example of your config? The field setup in the form generator as well as what leads saved?

**Comment by LBeckX** [comment]
This always happens when we have a checkbox menu.

Form field config:
![image](https://github.com/terminal42/contao-leads/assets/11272361/0680053c-0662-4da7-abc1-f568b0c0368b)

Form:
![image](https://github.com/terminal42/contao-leads/assets/11272361/4310bb3b-3baf-474e-b42f-23714ac72810)

Export configuration:
![image](https://github.com/terminal42/contao-leads/assets/11272361/4474834c-e5da-44b5-8729-b2d2ae84bed6)

Saved values and labels
![image](https://github.com/terminal42/contao-leads/assets/11272361/e6bd8e41-b9d7-41a2-8546-81bf9f36a106)

**Comment by aschempp** [comment]
that last screenshot is from the database, right? Do you also get that in an Excel export?

**Comment by chromagnon** [comment]
I have the same issue. Checkboxgroups, wether with one or multiple options checked, are exported in serialized form, as raw data, because thats the form how they are saved in the database. The target of the export doesn'z matter, csv, excel, pdf, its always in serialized form.

**Comment by Total-Reality** [comment]
I can also confirm the problem. It appears in version 3.0.4. 
The export was correct in version 1.4.33.

**Comment by SpeGal** [comment]
In the backend the stored array is showen correctly as e.g. "Samstag, Sonntag" if you click on the "data" button at the end of the line. But at the export it showes in the Excel table: a:2:{i:0;s:7:"Samstag";i:1;s:7:"Sonntag";}

It used to be formated correctly at the export. There must be a bug in the programming somewhere.

**Comment by aschempp** [comment]
Fixed in 5a7b9fedc6f2e36391d831b1e04a36cfd48f8713
