### ISSUE TITLE
Offer a possibility to export the data cron- or time-based

### ISSUE THREAD

**Issue by jscholtysik** [terminal42/contao-leads#15]
Hi is it possible to add a function that one can export the data at certain time periods via an adjustable cron job or something similar?

Example:
I have to provide an export file with formular data every night at 00:00 o'clock for a client, so that he is then able to continue processing the exported data in his system.

**Comment by Toflar** [comment]
There's now time based export options in 1.3, wanna give it a shot? :)

**Comment by aschempp** [comment]
This feature is available in the latest development version (Contao 4 only).
