### ISSUE TITLE
Datumsdarstellung im Backend

### ISSUE THREAD

**Issue by kroerig** [terminal42/contao-leads#150]
Hallo,

ich frage in einem Formular das Geburtsdatum ab. Klappt auch soweit. Im Excel-Export habe ich das Feld als Datum deklariert. Funktioniert auch.
Aber im Backend bekomme ich in der Datensatzansicht nur den Unix Timestamp.
![grafik](https://github.com/terminal42/contao-leads/assets/5148795/afbe5193-0594-4147-a30c-e63d260e6509)

Lässt sich das ändern, sodass auch hier ein lesbares Datum steht?

Danke.

**Comment by zoglo** [comment]
You could use the [processFormData](https://docs.contao.org/dev/reference/hooks/processFormData/) hook from Contao and handle how the data is saved 🤔

**Comment by kroerig** [comment]
Es geht hier nicht darum wie die Daten gespeichert werden, sondern wie sie angezeigt werden.

**Comment by zoglo** [comment]
> Es geht hier nicht darum wie die Daten gespeichert werden, sondern wie sie angezeigt werden.

Es geht hier nicht darum, wie die Daten angezeigt werden können, sondern darum, dass die Anzeige weiß, dass der integer ein timestamp vom type datum ist?

Wenn noch nicht vorhanden, kannst du hier einen PR bereitstellen, der auf eval date prüft und das bei der Ausgabe speichert?

Vielen Dank für deine Hilfe

**Comment by kroerig** [comment]
Ich bin nur kein Entwickler

**Comment by zoglo** [comment]
Hab den Link hier gefunden:
https://www.terminal42.ch/de/open-source

**Comment by aschempp** [comment]
Bitte nicht schliessen, es ist ja ein valider Fehler.

**Comment by kroerig** [comment]
Ist es ein Fehler?

Die Infobox gibt die Inhalte so wieder wie sie in der Datenbank stehen.
Der Kommentar von @zoglo hilft da wenig weiter. Ich selbst kann es nicht ändern und habe auch kein Budget es ändern zu lassen. Das sind bei mir alles Non-Profit-Freizeit-Projekte.

**Comment by aschempp** [comment]
Should be fixed in 1aa306375f2730b210481324104ec4f611a7288e
