### ISSUE TITLE
Datenexport auf Mobiltelefon

### ISSUE THREAD

**Issue by kroerig** [terminal42/contao-leads#153]
Am Desktop erhalte ich beim Klick auf den Export meine Daten im gewünschten Format (XLSX). Auf dem Smartphone lädt der Browser eine HTML-Datei, die sich mit nichts öffnen lässt.

Contao: 4.13.37
Leads: 3.0.4
Browser: Firefox unter Android 13

**Comment by aschempp** [comment]
Fixed in 4a80045b9921f2dc2903ac75b3ff5e74bdcab83c
