### ISSUE TITLE
Sending notifications later is no longer possible?

### ISSUE THREAD

**Issue by SpeGal** [terminal42/contao-leads#154]
Due to dependencies on other extensions, we have an installation where Leads 1.4.33 is still installed. There you could have a notification sent to the email address at the bottom of the inquiry list after each inquiry. We were very happy to use this because it meant we could simply send lost emails again quickly. You could also use “Edit multiple” to select all requests and, for example, send a further notification.

E.g. After submitting the form, seminar participants automatically received a confirmation email that the request had been received. Once an employee had processed this, he or she could then simply select another notification and, for example, send a registration confirmation or further information about the seminar and, for example, send a feedback link via the notifications afterwards.

Apparently the feature was dropped from Leads 3.x. Why?
This was such a good and important tool for us. Can we please have this back? :)

**Comment by aschempp** [comment]
Yes, the feature was dropped in the current version, simply because we internally didn't have any need for it. Also, this would be incompatible with Notification Center 2.0.

You might want to have a look at Notification Center Pro (https://extensions.terminal42.ch/de/notification-center-pro) which has a logging feature that allows you to re-send notifications (including modifications).

**Comment by SpeGal** [comment]
We have bought the Pro version in hopes the functionallity like before would be restored but sadly were disssappointed that the way it's handled in the Pro is nowhere near as good as it used to be :/

It is way too hard to explain to an average employee how to operate NCPro compared to the former version that was very intuitive and easy to understand. Maybe consider this as request for more usability and simplicity in this matter.

**Comment by aschempp** [comment]
Please feel free to get in touch by email about Notification Center Pro, maybe we can find something to improve for your use case. But the leads GitHub issue tracker isn't ideal for that 🙃
