### ISSUE TITLE
Individual export with Simple Tokens has no table header

### ISSUE THREAD

**Issue by oliverkieslich** [terminal42/contao-leads#155]
Hi,

I am using Leads version 3.0.4 with Contao 4.13.40.

When I trigger an individual export with Simple Tokens, the export data is correct. 
However, the export has no header, although I select this option in the export configuration and all data fields have a “Label for header”.
This behavior is independent of the selected file type for the export.

I see this error message in the log:

request.CRITICAL: Uncaught PHP Exception PhpOffice\PhpSpreadsheet\Exception: “Row and Column Ids must be positive integer values” at /www/htdocs/xxxxxxxxxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/CellAddress.php line 49 {“exception”:"[object] (PhpOffice\\PhpSpreadsheet\\Exception(code: 0): Row and Column Ids must be positive integer values at /www/htdocs/xxxxxxxxxx/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/CellAddress.php:49)”} []

I did some research on “PhpSpreadsheet” and this error and found this:

https://stackoverflow.com/questions/75162512/row-and-column-integer-error-when-calling-load
“This was caused by a bug in PHPSpreadsheet that was revealed by having a vertical break in row H0 for some reason.
Removing the breaks in the spreadsheet manually would also correct the problem but the latest version of PHPSpreadsheet has been fixed so it will not thrown an error if there is a vertical break in the first row.”

Is there any way to fix this problem?

Thanks for your help
Olli

**Comment by aschempp** [comment]
Fixed in ed179d5d3a2d99dc283b3a256db83d0647482387
