### ISSUE TITLE
Sorting of backend menu not alphabetical anymore

### ISSUE THREAD

**Issue by SpeGal** [terminal42/contao-leads#156]
It used to be so that the stored requests in the backend menu (on the left) were sorted alphabetically. Now they seem to be sorted by ID or timestamp or so. We found it way more helpful to have them sorted by alphabet. Was there a specific reason to change this? Would it be possible to either change it back or add a feature that allowes the administrator to chanege the sorting of the leads request in the back end menu on the left?

**Comment by aschempp** [comment]
It should be sorted alphabetically, but ce96c9763dd05d906d580ded865eb2b4a57f9541 might fix a potential issue.

**Comment by SpeGal** [comment]
This fixed it. Thank you!
