### ISSUE TITLE
Keine Anzeige der Inhalte bei Anfragen im BE

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-leads#16]
Contao 3.5.3
leads master 1.5? (Manuell installiert und den Modulordner nach leads umbenannt.)

Im BE habe ich ohne Composer installiert:
- haste 4.9.0
- MultiColumnWizard 3.3.3
- NamespaceClassLoader 1.0.2 (automatisch hinzugefügt)

Ich habe mal das Formular Contact aus der Demo in der DB in einer Tabelle my_form gespeichert. In den Bildern kann man die Einstellungen und die Ausgabe sehen.

Tabelle my_form:
![server24 webgo24 de_127 0 0 1_web36_db24_my_form_phpmyadmin_3 4 9_-_2015-09-30_14 23 26](https://cloud.githubusercontent.com/assets/1143013/10192898/f2e698a6-677f-11e5-8c54-9e482dcb1ad1.png)

Gespeicherte Datensätze:
![server24 webgo24 de_127 0 0 1_web36_db24_my_form_phpmyadmin_3 4 9_-_2015-09-30_14 24 51](https://cloud.githubusercontent.com/assets/1143013/10192912/040a89a8-6780-11e5-88cc-a2cdf52b7b79.png)

BE-Anfragen-Contact:
![contact_-_contao_open_source_cms_3 5_-_2015-09-30_14 20 34](https://cloud.githubusercontent.com/assets/1143013/10192920/13977430-6780-11e5-8587-ce42c7ff975c.png)

Formulardaten anzeigen:
![contact_-_contao_open_source_cms_3 5_-_2015-09-30_14 21 04](https://cloud.githubusercontent.com/assets/1143013/10192939/3258dee0-6780-11e5-99ab-839be29cea7a.png)

Formular Einstellungen:
![formulargenerator_ _das_formular_id_5_bearbeiten_-_contao_open_source_cms_3 5_-_2015-09-30_14 22 32](https://cloud.githubusercontent.com/assets/1143013/10192946/3f803258-6780-11e5-92c8-6fd86b367285.png)

Sollte doch eigentlich gehen, aber warum funktioniert das nicht?

**Comment by cliffparnitzky** [comment]
Das "Eingabe speichern" in Zieltabelle "my_form" hat gar nix mit leads zu tun .... das könntest du schon mal entfernen.

Dann ist noch wichtig in den Formularfeldern zu definieren, welche mit leads gespeichert werden sollen. Ist das nicht aktiv, wird auch nichts gespeichert.

**Comment by Aybee** [comment]
Ups, sorry, dann hatte ich das total missverstanden. Jetzt funktioniert es. Ich danke dir.

Gibt es eine Anleitung dazu? Wenn ich die Felder neu erzeugt hätte, wäre mir das Feld bestimmt aufgefallen, aber da die Felder ja schon existierten...

Noch eins, bevor ich ein neues Ticket dazu aufmache. ##salutation## gibt mir in der Liste **mrs** aus, also den Wert aus der Spalte **value**. Wäre es da nicht besser den Wert aus **label**, **Mrs.**,  auszugeben? Oder kann ich das auch irgendwo einstellen?

**Comment by aschempp** [comment]
Das lässt sich nicht einstellen. Du kannst aber Simple Tokens verwenden um das zu erreichen.

PS: eine Anleitung wäre doch eine schöne Mithilfe? ;-)

**Comment by Aybee** [comment]
Aber  ##salutation## ist doch schon ein Simple Token, oder? Oder gibt es sowas wie ##salutation.label##?
> PS: eine Anleitung wäre doch eine schöne Mithilfe? ;-)

Würde ja schon ausreichen, wenn das hier aus der README.md etwas ausführlicher wäre:
> All configuration can be done in the form generator from Contao. 

... Jedes Feld muss zum Speichern markiert werden. (alt: Die Speicherung eines jeden Feldes muss über das Feld **In Anfrage speichern** aktiviert werden.) Es muss keine extra Tabelle zum Speichern der Datensätze angelegt werden. Die Datensätze werden in den Tabellen tl_lead, tl_lead_data und tl_lead_export gespeichert.

**Comment by aschempp** [comment]
{if salutation="mr"}Mr.{elseif saluation="mrs"}Mrs.{endif}

**Comment by Aybee** [comment]
Ich würde dazu gerne ein eigenes Ticket aufmachen mit dem Wunsch, dass der Simple Token immer den label anstatt des values ausgibt. Weil ich denke, dass man dort in der Listenansicht immer den label sehen möchte. Wäre das in Ordnung?

**Comment by aschempp** [comment]
Ich glaube das wäre nicht korrekt. Wir sollten aber eine bessere Möglichkeit als das if/else schaffen. Zum Beispiel mit einem allgemeinen InsertTag welcher auch im Notification Center verwendet werden kann.

**Comment by Aybee** [comment]
Ja, ok. Dann würde ich sowas wie ##salutation|label## o.ä. vorschlagen.

**Comment by aschempp** [comment]
das geht nicht, denn wenn du ein Feld mit demselben Namen hast gibts nen Konflikt. Ich denke eher sowas wie `{{option_label::ID::##salutation##}}`

**Comment by Toflar** [comment]
Wir haben schon allgemeine (via `haste`) für die Datumsformatierung. Den könnten wir da ergänzen.

**Comment by aschempp** [comment]
The next version (1.6) will support Haste 4.10, which allows to format such data (e.g. `{{option_label::ID::##salutation##}}`).
