### ISSUE TITLE
No space between attributes

### ISSUE THREAD

**Issue by Aybee** [terminal42/contao-leads#19]
Line 199 in Leads.php results in no space between attributes (`...verwalten."style="background...`)
https://github.com/terminal42/contao-leads/blob/master/library/Leads/Leads.php#L199
```html
<ul class="tl_level_2">
  <li>
  <a href="contao/main.php?do=lead&master=6" class="navigation leads" title="Anfragen für Formular &quot;Leads-Formular&quot; verwalten."style="background-image:url('system/modules/leads/assets/icon.png')">Leads-Formular</a>
  </li>
</ul>
```
Possible solution
```php
// -
'icon'      => 'style="background-image:url(\'system/modules/leads/assets/icon.png\')"',
// +
'icon'      => ' style="background-image:url(\'system/modules/leads/assets/icon.png\')"',
```

**Comment by aschempp** [comment]
Stupid, but true… https://github.com/contao/core/blob/master/system/modules/core/classes/BackendUser.php#L562

Behoben in be10e12122453a5a645df7deb90ae11127bef7b6

**Comment by Aybee** [comment]
Yes, looks strange. Why does this not work? I don't know.
```php
'icon'      => 'system/modules/leads/assets/icon.png',
```
