### ISSUE TITLE
creation date will not be exported

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-leads#22]
I've set up a saving of some form data and I also set up an export konfiguration. There I have the field "Date created" with the settings in the following screenshot. When I click the blue i icon in the data overview I see the "Received" date, but when I export/download the csv with the data, the field of date created is empty. With the option "Export all data" the column of "Date created" is empty, too.

Contao 3.5.9, terminal42/contao-leads 1.2.1
<img width="886" alt="screenshot 2016-04-27 11 13 10" src="https://cloud.githubusercontent.com/assets/1232819/14847572/a24b7274-0c69-11e6-92a6-71dfb8080056.png">

**Comment by qzminski** [comment]
Should be fixed in 7cdce76.

**Comment by frontendschlampe** [comment]
ui ... I didn't noticed your commit! I'm sorry.

It's working. Big Thanks.
