### ISSUE TITLE
leads are shown for user even if not enabled

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-leads#23]
If you do not enable the leads backend module in the rights settings for a (non-admin) backend user:

![leadsmodule](https://cloud.githubusercontent.com/assets/4970961/15780884/f244d624-29a3-11e6-863f-a381cc8efa8b.png)

the leads from the allowed forms will still be shown in the left bar:

![leadsbug2](https://cloud.githubusercontent.com/assets/4970961/15780969/5d08047c-29a4-11e6-8842-09b69333c9cb.png) ![leadsbug3](https://cloud.githubusercontent.com/assets/4970961/15780975/62918b70-29a4-11e6-9b94-dd352106f7d2.png) ![leadsbug](https://cloud.githubusercontent.com/assets/4970961/15780780/8f950d32-29a3-11e6-85c4-a446a337cf5a.png)

**Comment by aschempp** [comment]
Fixed in 93d69a2
