### ISSUE TITLE
Datumsumwandlung beim Speichern

### ISSUE THREAD

**Issue by felixpfeiffer** [terminal42/contao-leads#25]
Hallo,
ist ein Formularfeld als Datum definiert, wird dieses an Hand der Datumsdefinition in der localconfig.php umgewandelt.
In mehrsprachigen Seiten hat man aber unter Umständen unterschiedliche Datumsformate. Damit schlägt die Umwandlung fehl, wenn dies nicht korrekt eingegeben ist.
Spricht etwas dagegen, die Formatdefinition nicht aus der localconfig sondern aus dem Page-Obejkt zu ziehen?

**Comment by Toflar** [comment]
Kannst du versuchen die Zeile https://github.com/terminal42/contao-leads/blob/master/library/Leads/Leads.php#L44 entsprechend anzupassen?

Müsste dann wohl irgendwie so aussehen:

```php
$key = $objField->rgxp . 'Format';
$format = isset($GLOBALS['objPage']) ? $GLOBALS['objPage']->{$key} : $GLOBALS['TL_CONFIG'][$key];
$objDate = new \Date($varValue, $GLOBALS['TL_CONFIG'][$format]);
```

**Comment by Toflar** [comment]
@felixpfeiffer News?

**Comment by Toflar** [comment]
Fixed in 93f48cdaf5115e7f269dbd07092178bb24d50b40.
