### ISSUE TITLE
Fatal Error Allowed memory size ... exhausted

### ISSUE THREAD

**Issue by intradesign** [terminal42/contao-leads#28]
Moin zusammen,

ich habe gestern festgestellt, dass das schon früher aufgetauchte Allowed memory size ... exhausted Problem scheinbar dann ausgelöst wird, wenn in einem der SimpleTokens ein Bindestrich verwendet wird. Dabei ist es egal, ob es ein entsprechendes Formularfeld gibt oder nicht.

Wenn ich also im Formulargenerator in der "DatensatzBezeichnung" z.B. ##test-test## eingebe und anschließend die zu dem Formular gehörenden Anfragen öffnen möchte, wird der Fehler ausgegeben.

`Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65484 bytes) in .../system/modules/core/library/Contao/Config.php on line 50
`

Die Fehlermeldung hatte ich übrigens auch beim Versenden von Formulardaten mit dem Notification Center, bin mir aber nicht sicher, ob das mit dem Bindestrich zusammen hängt und das ist auch schon einige Zeit her.

Außerdem ist mir aufgefallen, dass es eine weitere Fehlermeldung gibt, wenn man in der Auflistung der Anfragen auf das blaue i-Icon klickt. Dann erscheint in einer Lightbox folgende Meldung dreimal unterneinaner:

```
Warning: include(/var/www/vhosts/tbv.intrahosting.xyz/httpdocs/system/modules/leads/templates/be_leads_show.html5): failed to open stream: No such file or directory in system/modules/core/library/Contao/BaseTemplate.php on line 88
#0 system/modules/core/library/Contao/BaseTemplate.php(88): __error(2, 'include(/var/ww...', '/var/www/vhosts...', 88, Array)
#1 system/modules/core/library/Contao/BaseTemplate.php(88): Contao\BaseTemplate::parse()
#2 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 system/modules/core/classes/BackendTemplate.php(34): Contao\Template->parse()
#4 system/cache/dca/tl_lead.php(342): Contao\BackendTemplate->parse()
#5 system/modules/core/classes/Backend.php(430): tl_lead->show(Object(Contao\DC_Table))
#6 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('lead')
#7 contao/main.php(20): Contao\BackendMain->run()
#8 {main}
```

Vielen Dank und viele Grüße
Timo Mackowiak

**Comment by Toflar** [comment]
Das ist eine bekannte Limitierung. Du darfst schlichtweg keine Tokens mit `-` verwenden. Ab Contao 3.5.16 wird das aber funktionieren. Das fehlende Template ist wohl auf eine nicht vollständige Installation von Leads zurück zu führen. Es ist nämlich [da](https://github.com/terminal42/contao-leads/blob/master/templates/be_leads_show.html5).

**Comment by intradesign** [comment]
Hallo und vielen Dank für die Info!

Achso, ich habe nirgends etwas über den Bindestrich gefunden und war schon recht verzweifelt… nur dass bei anderen dieselbe Fehlermeldung aufgetaucht ist und irgendwie niemand eine Lösung hatte.
Aber nun funkrioniert es ja.

Wegen des Templates: hilft da, einfach nochmal das leads-Verzeichnis zu überschreiben?

Vielen Dank und viele Grüße
Timo

INTRADESIGN | Timo Mackowiak | Kattenescher Weg 15a | 28277 Bremen | Tel 0421-52401239 | Mobil 0173-5237884 | timo@intradesign.xyz | USt-IdNr. DE259414283

Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail sind nicht gestattet.

THINK before printing!

Am 26. August 2016 um 20:26:28, Yanick Witschi (notifications@github.com) schrieb:

Das ist eine bekannte Limitierung. Du darfst schlichtweg keine Tokens mit - verwenden. Ab Contao 3.5.16 wird das aber funktionieren. Das fehlende Template ist wohl auf eine nicht vollständige Installation von Leads zurück zu führen. Es ist nämlich da.

**Comment by Toflar** [comment]
> Wegen des Templates: hilft da, einfach nochmal das leads-Verzeichnis zu überschreiben?

Ich denke schon, ja.

**Comment by cliffparnitzky** [comment]
@Toflar: Wäre vlt. ein kurzer Hinweis bzgl. der Bindestrich-Limitierung bei SimpleTokens in der Readme sinnvoll ??? Dann kann man darauf verweisen. Beim NC passiert das ja auch immer mal wieder.

**Comment by Toflar** [comment]
Nein, ab Contao 3.5.16 wird es ja funktionieren. Es liegt ja auch nicht an NC sondern an Contao. Du kannst auch im Newsletter bei Contao keine `-` verwenden (bisher).

**Comment by Toflar** [comment]
Wir könnten in den offiziellen Contao Docs erwähnen, dass die Zeichen `=!<>` in Tokens nicht erlaubt sind, da das Operatoren sind für die `{if`-Anweisungen.
