### ISSUE TITLE
Manual installation produces error

### ISSUE THREAD

**Issue by jenda77** [terminal42/contao-leads#29]
Hello, 

today I have tried to install your extension manually because I don´t use composer. Unfortunately, as I was trying to update the database it appeared an error. Before I had deleted the cache. 

```
Warning: in_array() expects parameter 2 to be array, null given in system/modules/core/library/Contao/System.php on line 160
#0 [internal function]: __error(2, 'in_array() expe…', '/homepages/46/d…', 160, Array)
#1 system/modules/core/library/Contao/System.php(160): in_array('getInstance', NULL)
#2 system/modules/core/library/Contao/System.php(340): Contao\System::importStatic('Leads\\Leads')
#3 system/modules/core/controllers/BackendInstall.php(43): Contao\System::loadLanguageFile('default')
#4 contao/install.php(23): Contao\BackendInstall->__construct()
#5 {main}

Fatal error: Class 'Leads\Leads' not found in /homepages/46/d570078274/htdocs/system/modules/core/library/Contao/System.php on line 160
```

How can I fix it?

**Comment by Toflar** [comment]
You cannot install it manually. Composer needs to generate the autoload file.

**Comment by jenda77** [comment]
What a pity. Then I cannot use it. Could you create a autoload file separentley for the manuell installation or write the code for it in your Readme-file? It would be nice. Thank you.

**Comment by fritzmg** [comment]
@jenda77 you should post this in the official support forum, not here.
