### ISSUE TITLE
OutOfBoundsException

### ISSUE THREAD

**Issue by NicolasGoerlach** [terminal42/contao-leads#30]
Hi,
Wenn man ein Textfeld anlegt und es auf den Eingabewert "Datum" überprüft, "In Anfrage speichern" auf "ja" setzt, es speichert, und  anschließend den Feldtyp von "Textfeld"auf  z.B. "Select-Menü" ändert, bleibt die Eingabeüberprüfung weiterhin bestehen und es kommt im Frontend beim Absenden des Formulars zu einem OutOfBoundsException Fehler.

Sobald man "In Anfrage speichern" auf "Nein" setzt, geht es ohne Problem durch.

Hier die ganze Meldung:
Fatal error: Uncaught exception OutOfBoundsException with message Invalid date "test" thrown in system/modules/core/library/Contao/Date.php on line 438
#0 system/modules/core/library/Contao/Date.php(79): Contao\Date->dateToUnix()
#1 composer/vendor/terminal42/contao-leads/library/Leads/Leads.php(44): Contao\Date->__construct('test', 'd.m.Y')
#2 composer/vendor/terminal42/contao-leads/library/Leads/Leads.php(251): Leads\Leads::prepareValue('test', Object(Contao\Database\Mysql\Result))
#3 system/modules/core/forms/Form.php(544): Leads\Leads->processFormData(Array, Array, Array, Array, Object(Contao\Form))
#4 system/modules/core/forms/Form.php(255): Contao\Form->processFormData(Array, Array, Array)
#5 system/modules/core/classes/Hybrid.php(239): Contao\Form->compile()
#6 system/modules/core/forms/Form.php(90): Contao\Hybrid->generate()
#7 system/modules/core/library/Contao/Controller.php(484): Contao\Form->generate()
#8 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#14 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}

**Comment by fritzmg** [comment]
Selbes Problem hatte auch gerade ein Kunde. Ein Feld war zuvor auf `Text` gestellt mit der Einstellung, dass auf `Datum` geprüft werden soll. Danach wurde das Feld in diesem Fall auf ein `Radio` umgestellt, mit Eingabewerten, die nicht einem Datum entsprechen. `contao-leads` erwartet aber dann trotzdem immer noch, dass es sich bei dem Wert um ein Datum handelt.

**Comment by aschempp** [comment]
das ist eine "Known Limitation" von Contao, die Lösung dafür ist einfach vor dem ändern des Typs die Prüfung zu deaktivieren.

**Comment by fritzmg** [comment]
Naja, das ist ersten umständlich und zweitens müsste man das Redakteuren beibringen. Darüberhinaus wäre das ja inkonsistent, da man so etwas sonst nirgendwo beachten muss.

Es würde doch reichen [diesen Code](https://github.com/terminal42/contao-leads/blob/1.4.0/library/Leads/Leads.php#L42-L48) nur dann auszuführen, wenn das Feld von einem gewissen Typ ist. Eine Überprüfung für den Feld Typ passiert ja zB auch schon [hier](https://github.com/terminal42/contao-leads/blob/1.4.0/library/Leads/Leads.php#L28-L31), also warum nicht auch für die Generierung der Timestamps.

**Comment by aschempp** [comment]
Fixed in 462cc608db7097fa18d1a4f7ce6d0dea55844cf9

**Comment by Lixus** [comment]
I had the same problem still with contao 4.13 and contao-leads 3.0.4
