### ISSUE TITLE
configurable CSV export

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-leads#31]
If you use a German regional setting in your (Windows) OS for example, Microsoft Excel (Windows) cannot properly open CSV files directly. With German regional settings it expects the delimiter to be `;`, since the decimal point with German regional settings is `,`. Furthermore Microsoft Excel (Windows) needs the Byte Order Mark for UTF-8 support.

So further CSV export options could be:

* delimiter (`,` by default)
* decimal point (for `number_format`, may be changed automatically according to the delimiter)
* add Byte Order Mark

See these test files for example: [csv_test.zip](https://github.com/terminal42/contao-leads/files/626802/csv_test.zip)

Screenshots in Microsoft Excel 2016 (Windows):

![without_bom](https://cloud.githubusercontent.com/assets/4970961/20829477/839e4b0c-b87c-11e6-86a4-bd834991ef1a.png) ![with_bom](https://cloud.githubusercontent.com/assets/4970961/20829478/839ee102-b87c-11e6-8089-a5b6c57cbfae.png)

**Comment by aschempp** [comment]
Why don't you use the excel export?

**Comment by fritzmg** [comment]
Oh, has that been added? I am sorry, I was testing in a Contao 3.2 installation where the most recent version of `contao-leads` is not available. I missed that that feature was added.

**Comment by fritzmg** [comment]
Oh, I see, apparently you just have to install `phpoffice/phpexcel`? The `README.md` only mentions 
> (CSV and - you need to install the "excel" extension)

**Comment by fritzmg** [comment]
See #32
