### ISSUE TITLE
Contao backend slows down with any click

### ISSUE THREAD

**Issue by oliverkieslich** [terminal42/contao-leads#33]
Hi,

first let me say thank you for this great module!!!

I have a project with about 40 Leads. This slows down the whole Contao backend because of this complex database query from system/modules/leads/Library/Leads/Leads.php:

 query] => SELECT f.id, f.title, IF(f.leadMenuLabel='', f.title, f.leadMenuLabel) AS leadMenuLabel
                FROM tl_form f
                LEFT JOIN tl_lead l ON l.master_id=f.id
                WHERE leadEnabled='1' AND leadMaster=0
            UNION
                SELECT l.master_id AS id, IFNULL(f.title, CONCAT('ID ', l.master_id)) AS title, IFNULL(IF(f.leadMenuLabel='', f.title, f.leadMenuLabel), CONCAT('ID ', l.master_id)) AS leadMenuLabel
                FROM tl_lead l
                LEFT JOIN tl_form f ON l.master_id=f.id
                WHERE ISNULL(f.id)
                ORDER BY leadMenuLabel
                    [explain] => Array
                        (
                            [id] => 1
                            [select_type] => PRIMARY
                            [table] => f
                            [type] => ALL
                            [possible_keys] => 
                            [key] => 
                            [key_len] => 
                            [ref] => 
                            [rows] => 37
                            [Extra] => Using where
                        )

                    [returned] => 40 row(s) returned
                    [duration] => 33.022,939 ms !!!!!!!!!!!!!!!!!!!!

This query "only" generates the list of Leads in order to make it clickable in the Contao backend (wich is at last useful) . But every click in the contao backend causes this query again without caching and this slows down the backend and frontend while database is under heavy work.  

Is there a possibility to fix this issue?

Thanks a  lot

Oliver

**Comment by Toflar** [comment]
@aschempp why is this query so complicated? Doesn't make sense to me. All the data is always stored in the master forms. Why don't we simply fetch all master forms only there? Can you shed some light on why there's a `UNION` call there? I'll try to fix it then because that indeed looks weird.

**Comment by aschempp** [comment]
The background is that the navigation shows items for all forms in the form generator (even without lead) and all master leads (even if the form has been deleted). It can probably be optimized with SQL indexes or two separate queries.

**Comment by Toflar** [comment]
I think there were two issues here:

* database indexes missing: added in 7fc47811d89ae63956f10880856d16d89a2f604e
* UNION query did not DISTINCT select: reworked and simplified in 2662299c02a333941b38862bfd2680a22bc15ef5

@oliverkieslich can you please test the hotfix/1.4.2 branch and see if it solves the issue for you. Depending on your feedback I'd then go on to release the new version :-)

**Comment by oliverkieslich** [comment]
It works like a charme :-)

Thank you very much and happy xmas!

**Comment by Toflar** [comment]
Tagged and released. You're welcome, happy xmas :-)
