### ISSUE TITLE
XLSX-Export über das Frontend

### ISSUE THREAD

**Issue by Schmidty2** [terminal42/contao-leads#36]
Ist es möglich, ein Modul einzubauen, mit dem ein vordefinierter Excel-Export (*.xlsx) über das Frontend zum Download angeboten werden kann?
Der Download soll über den Contao-Frontendlogin geschützt werden können.

Beispiel: Anmeldung zu einer Veranstaltung, mehrere Organisatoren der Veranstaltung sollen die Anmeldedaten (bzw. Teile davon - entsprechend dem vorkonfiguriertem XLSX-Export) exportieren können. Sonst müsste für diesen Personenkreis nur für den Export ein stark eingeschränkter Backendzugang eingerichtet werden.

**Comment by Toflar** [comment]
Ist bestimmt möglich.

**Comment by aschempp** [comment]
Ich bin noch immer der Meinung dass das Modul keine Frontend-Funktionen enthalten sollte. Liesse sich über eine zusätzliche Erweiterung selber lösen.
