### ISSUE TITLE
Form field label and tl_lead_data label

### ISSUE THREAD

**Issue by tsarma** [terminal42/contao-leads#37]
In my opinion, the function ```Leads::prepareLabel()``` should return ```$objField->label```. Otherwise in table ```tl_lead_data```, the fields ```value```and ```label``` has same entry, which is redundant. Or is there another reason for that.

PS: Thanks for introducing to this module. It was hard to find it on my own, as it is not listed in Extension Repo. (May be due to preferred listing on packagist)

**Comment by aschempp** [comment]
According to the DocBlock, `Leads::prepareLabel()` is used to store the value in the database?

**Comment by tsarma** [comment]
Yes according to the DocBlock, ```Leads::prepareLabel()``` is used to get a label for the form input value to store in database. That in my opinion should be the label of the form field, not the value of form field. Right now it is storing the value of form fields.

Thus it should return only the label, may something like
```php 
    public static function prepareLabel($varValue, $objField)
    {
        return ($objField->label)?:$objField->name;
    }
```

**Comment by aschempp** [comment]
I'm sorry this might be confusing. It is not supposed to be the widget label, but the value label (e.g. for Checkboxes).

**Comment by tsarma** [comment]
Ok I have here screen capture of what I mean.

Originally: Both label and value has the same value in table ```tl_lead_data```
![ori](https://cloud.githubusercontent.com/assets/683894/26154124/8af398c0-3b0e-11e7-9730-a481b5e3020c.png)

After proposed change mentioned above:
![changed](https://cloud.githubusercontent.com/assets/683894/26154162/b3a63aa2-3b0e-11e7-95ea-f4eb5094391a.png)

**Comment by tsarma** [comment]
Oh, I get it now. what you mean by, it is not the widget label but the value label.
