### ISSUE TITLE
Export: Individueller Export nicht mehr wählbar

### ISSUE THREAD

**Issue by Xendiadyon** [terminal42/contao-leads#39]
Irgendwie ist seit kurzem in den Export-Optionen bei "Individueller Export" nichts mehr wählbar/einstellbar:
![image](https://cloud.githubusercontent.com/assets/2657385/26314805/60b5fd1e-3f0f-11e7-970a-014fa0ea6353.png)

Da konnte ich vorher jedes einzelne Feld genau definieren.

Tritt das nur bei mir auf oder habt ihr das auch?
Ich habe Contao 4 und Erweiterungen per Composer aktualisiert, wüsste aber nicht, woran es jetzt konkret liegen könnte.

Außerdem stellt sich bei uns die Backend-Sprache (z.T.) einfach mal so auf Englisch um (sodass wir dann einen Denglisch-Sprachmix im Backend haben). Ich habe Leads im Verdacht, kann es aber noch nicht zweifelsfrei bestätigen.

**Comment by Toflar** [comment]
> Außerdem stellt sich bei uns die Backend-Sprache (z.T.) einfach mal so auf Englisch um (sodass wir dann einen Denglisch-Sprachmix im Backend haben). Ich habe Leads im Verdacht, kann es aber noch nicht zweifelsfrei bestätigen.

Das dürfte eher am internen Cache liegen, der kaputt war. Mal alles löschen, Contao updaten und dann sollte das passen.

Und die fehlenden Felder: Sicher dass der MCW korrekt installiert wurde?

**Comment by Xendiadyon** [comment]
Das Sprach-Problem war wahrscheinlich das hier: https://github.com/contao/core-bundle/issues/812
https://github.com/contao/core-bundle/issues/784

Das Contao-Update hat leider etwas Probleme gemacht, jetzt geht es wieder: https://github.com/contao/core-bundle/issues/845

Und ja, du hattest Recht: MCW war nicht korrekt eingebunden, der Eintrag in der AppKernel.php war auskommentiert...

Danke für deine Hilfe.
