### ISSUE TITLE
Issue with file upload field

### ISSUE THREAD

**Issue by JLBA** [terminal42/contao-leads#4]
Hi,
Leads works well but it doesn't save file upload data (like the path or url of the file).
The field isn't even displayed in the Leads. And so isn't exported in csv nor xls.
What to do ?
Thanks

**Comment by JLBA** [comment]
Hi Kamil,

I want to test the last modifications you’ve made to Leads with the 2.11 version of Contao where I needed it but I got an error when trying to install it.
I can’t upgrade to another version of Contao because the website is using Catalog.

Thanks for your help. 

JL Test
jltest@free.fr

**Comment by qzminski** [comment]
The Leads does not support Contao 2.11 anymore.

**Comment by JLBA** [comment]
Thanks for your answer. 
I was afraid of that but when I created the issues you fixed, it was to work with Contao 2.11. At that moment, Contao 2.11 was still the prolonged LTS version but Metamodels wasn’t yet ready for it. I’m in an impasse…

There is still on the github a special version for Contao 2.11. Is it possible I add to it the different fixes ?


JL Test
jltest@free.fr
