### ISSUE TITLE
Contao 4: leads not visible in backend

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-leads#41]
Under Contao 4(.4) the leads are not visible in the backend. I have enabled __Store leads__ and given a __Navigation label__ plus __Record label__, but the leads will not appear in the left menu pane under "Leads". The leads are stored as expected in the database though. I also tried not using a custom __Navigation label__, but the leads are still not visible. This was tested with an admin user.

**Comment by fritzmg** [comment]
Might be a core-bundle bug. The HTML markup signifies, that the "Leads" section is active/open, because it gets the class `node-expanded`. However, There is no `leads` entry in the `backend_modules` session data. Instead, if you open the "Leads" link twice in a new tab, the leads will be visible.

**Comment by aschempp** [comment]
It works fine in my backend, maybe because the section is not collapsed for me…?

**Comment by fritzmg** [comment]
> It works fine in my backend, maybe because the section is not collapsed for me…?

Yeah, I think this problem occurs if you try to open the "Leads" section in the left pane, before any leads are defined. I'll see if I can reproduce that again.

**Comment by webmurkser** [comment]
bei mir das gleiche Problem - `tl_lead` und `tl_lead_data` enthalten auch Daten - im Backend sehe ich die Überschrift "Anfragen" aber keinen Unterpunkt mit den Daten des Formulars. 

Contao 4.4.0 installiert über den contao-manager

google translate: 
same problem here - `tl_lead` and` tl_lead_data` also contain data - in the backend I see the heading "Anfragen" but no subpoint with the data of the form.

**Comment by aschempp** [comment]
Fixed in version 1.4.7
