### ISSUE TITLE
Formular is selectable even if backend user has no permissions

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-leads#47]
In this example the backend user has no permissions to the Formular "Kartenbestellungen (Backup-Formular)" but can select it in "Hauptkonfiguration"

![image](https://user-images.githubusercontent.com/6831223/29664898-e5e10d2e-88d1-11e7-92dc-fe9117a7f61c.png)

**Comment by aschempp** [comment]
I'm not sure this is a bug. If a user can only see forms in his language, he cannot assign the master form? On the other hand, he could not see the leads from that form either…

**Comment by aschempp** [comment]
@terminal42/pilots

**Comment by qzminski** [comment]
The dropdown should contain only the forms that the user has access to.

**Comment by mpitz** [comment]
But it doesn't. So it's a bug?

**Comment by qzminski** [comment]
Fixed in a52ef9f.
