### ISSUE TITLE
Fehler bei Insert in tl_leads

### ISSUE THREAD

**Issue by mpunkt** [terminal42/contao-leads#50]
`An exception occurred while executing 'INSERT INTO tl_lead ... VALUES ...' String data, right truncated: 1406 Data too long for column 'language'.`

Laut Tabellenstruktur ist die Spalte 'language' vom Typ varchar(2). In der INSERT-Anweisung soll in meinem Fall der Wert 'de_DE' eingefügt werden.

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-leads/commit/0e066f2f4aa94061fa0e7e2f786a394183a26c2f.
