### ISSUE TITLE
tl_lead_data contains no records

### ISSUE THREAD

**Issue by Brubbel66** [terminal42/contao-leads#51]
C4.4.7, NC1.4.2, CL1.4.7, mp_forms3.0.4
NC in conjunction with mp_forms works perfect. Additionally I would like to use leads to display the form data in the backend but it only shows the Simple Tokens itselves (except of the ##created## Token).

![grafik](https://user-images.githubusercontent.com/13145836/32827793-9b27be7e-c9ed-11e7-9a2e-34f2396e720d.png)

In the database, the table tl_lead_data is completely empty, which is probably the reason. This is the first time I use this under C4. Formerly I used leads the same way with C3.5 without problems.

Anything that I need to change with C4 or a bug?

**Comment by aschempp** [comment]
Did you configure the fields to be actually stored in Leads?

**Comment by Brubbel66** [comment]
Not sure what you mean. This?:
![grafik](https://user-images.githubusercontent.com/13145836/32901919-5f64a4ce-caf1-11e7-96e5-b0e4fad3669e.png)

**Comment by fritzmg** [comment]
You need to activate for each form field as well.

**Comment by Brubbel66** [comment]
<Head on table edge />that´s it. I´m sorry to have wasted your time and thanks a lot for the hints.
