### ISSUE TITLE
Do not convert dates to timestamps

### ISSUE THREAD

**Issue by fritzmg** [terminal42/contao-leads#53]
Consider the following example and reproduction:

1. Set the timezone of your Contao Installation to `CET` in the system settings.
2. Create a form with a text input field named `birthday`.
3. Set the validation of the text field to _Date_.
4. Configure the form and field to be saved into a lead.
5. Submit the form with the date `1980-09-27` for example.
6. Look at the leads entry in the back end, it will display `[1980-09-27]` as the value.
7. Set the timezone of your Contao Installation to `GMT` in the system settings.
8. Look at the leads entry in the back end, it will display `[1980-09-26]` as the value.

Contao Leads makes the assumption that a date field is automatically a timezone-transformable moment in time and thus transforms it to a timestamp. But clearly, birthdays for example should never be adjusted to a timezone, thus it makes no sense to save birthdays as timestamps.

**Comment by Toflar** [comment]
Imho that has absolutely nothing to do with leads. Any date form text field in Contao makes that assumption and it would be the same everywhere with birthdays.

**Comment by fritzmg** [comment]
Contao Leads handles front end forms. Contao makes no such assumptions about data submitted from front end forms. A date text field with the content `27.09.1980` will stay untouched. Contao Leads converts it into a timestamp here: https://github.com/terminal42/contao-leads/blob/1.4.9/library/Leads/Leads.php#L475

**Comment by Toflar** [comment]
Anyway, not something we can fix in my opinion. Cannot help here.

**Comment by fritzmg** [comment]
Why not? Instead of converting a date, datim or time field to a timestamp, simply save the textual representation.
