### ISSUE TITLE
Date / Time not converted in list view

### ISSUE THREAD

**Issue by Metis77** [terminal42/contao-leads#56]
if a form text field input validation is set to date or time, the date or time is stored as Unix Epoch timestamp like `1539122400`. Ok so far.

In the list view of leads where the record label has been configures with something like `##date##` or `##time##` those date/time timestamps are not converted back.
On the other hand it is converted back correctly in the "show details" and in the "show field data" view and looks like `[10.10.2018]`

Tested with Contao 3.5.31.

**Comment by fritzmg** [comment]
See also #53

**Comment by aschempp** [comment]
I think you need to use an insert tag to format the date in the list.

**Comment by Metis77** [comment]
@aschempp could you offer an example?
How can I combine the form field name like ##date## with an insert tag?

**Comment by Toflar** [comment]
Haste provides such an insert tag: https://github.com/codefog/contao-haste/blob/master/docs/Util/InsertTags.md

**Comment by Metis77** [comment]
great, thank you!
I think this tip is worth to be mentioned in the readme.
