### ISSUE TITLE
The composer suggest for excel is phpoffice/phpexcel

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-leads#58]
Package `phpoffice/phpexcel` is abandoned, you should avoid using it. 
Use `phpoffice/phpspreadsheet` instead.

**Comment by fritzmg** [comment]
That would require a rewrite of the excel export. As long as there is no problem or bug, using the abandoned package should not be a problem.

**Comment by zonky2** [comment]
should be added https://github.com/terminal42/contao-leads/commit/432c96131b2848c9e46a4541c38ef501938513d7

**Comment by fritzmg** [comment]
What is the status on this? The README suggests that Leads is compatible with `phpoffice/phpspreadsheet` _and_ `phpoffice/phpexcel`. However, the `composer.json` still only suggets `phpoffice/phpexcel`.

**Comment by richardhj** [comment]
We can switch the suggest to phpspreadsheet. That should be fine.

**Comment by fritzmg** [comment]
Yeah people on the forum are still confused about that and scared of the "abandoned" message ;)

**Comment by zonky2** [comment]
currently both are supported - if there is only one, I also like to change the readme

**Comment by fritzmg** [comment]
The README does not need to be changed if both are supported.

**Comment by richardhj** [comment]
Changed in 97e547645699b3454899e1b325316ef700092b38.

**Comment by zonky2** [comment]
delete `|| (class_exists('PHPExcel') ` in https://github.com/terminal42/contao-leads/blob/master/library/Leads/Exporter/AbstractExcelExporter.php#L31 or mark as deprecated

**Comment by richardhj** [comment]
We do not need to mark it as deprecated, because Composer is already doing it.
