### ISSUE TITLE
Problem beim Export von Checkboxen mit nur einer Auswahlmöglichkeit

### ISSUE THREAD

**Issue by frontendschlampe** [terminal42/contao-leads#59]
Ich habe eine Formularfeld *Checkbox-Menü* mit dem Feldnamen "conditions" und der Feldbezeichnung "Bedingungen" mit nur einer Option (Wert "yes", Bezeichnung "Ja, ich akzeptiere ...").

Wenn ich jetzt einen Export konfiguriere mit "Alle Daten exportieren", dann exportiert er alles korrekt (und auch in der Backendansicht ist alles korrekt):

```"Bedingungen [yes]"```

Der Kunde will aber halt nicht die Bezeichnung und den Wert in der Tabelle haben, sondern nur den Wert pro Feld. Also habe ich auf "individueller Export" umgestellt und die Felder entsprechend ausgefüllt. "Wert" --> "Nur den Wert", "Format" --> "Rohdaten" ... alle Felder werden korrekt exportiert, aber bei der o.g. Checkbox mit nur einer Option wird immer "nein" in der Spalte angezeigt.

```nein```

Wenn ich bei "Wert" umstelle auf "Bezeichnung und Wert" dann wird es auch falsch ausgegeben:

```"Bedingungen [nein]"```

Andere Checkbox-Felder mit mehr als einer Option geben den Wert korrekt aus!

**Comment by cmartin6** [comment]
Ich habe nach wie vor das selbe Problem. Gibt es hierzu einen Fix?

**Comment by aschempp** [comment]
Ich denke es ist so gedacht, dass bei einzelnen Checkboxen "1" als Wert verwendet werden sollte. Dann erscheint korrekt "ja" oder "nein" als Wert beim Export.
