### ISSUE TITLE
Enhancement: Encryption

### ISSUE THREAD

**Issue by rburch** [terminal42/contao-leads#60]
I really like this module and use it often. Can the data be encrypted with this module? We're trying to be GDPR compliant.

**Comment by cliffparnitzky** [comment]
You can use this additional extension: https://github.com/hofff/contao-leads-encryption

**Comment by aschempp** [comment]
Can someone explain to me why encryption would change/help anything in regards to GDPR?

**Comment by cliffparnitzky** [comment]
@aschempp Maybe, because https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Pseudonymisation ... but that's just a guess.

**Comment by aschempp** [comment]
> The GDPR requires for the additional information (such as the decryption key) to be kept separately from the pseudonymised data.

This is absolutely not the case if the server is able to encrypt and decrypt the values, so the encryption is *useless*...

**Comment by fritzmg** [comment]
I agree with @aschempp , however you could argue that the encryption key is at least stored separately from the database. So if the database is compromised, but the file system is not, the data cannot be restored.

**Comment by Toflar** [comment]
Which is not related to leads at all.

**Comment by rburch** [comment]
Yes, I was referring to pseudonymisation. Still trying to make sense of the law but it seems that they want personal data encrypted which is a huge undertaking. So for Leads, because it can and often does store personal data, it seems like having it encrypted is a step towards the compliance the law prefers. Maybe Contao tokenization already gets us far enough. At least for now.

**Comment by aschempp** [comment]
Also be aware that the mentioned library apparently uses the Contao encryption library, which is no longer working in PHP 7.2 😉
