### ISSUE TITLE
Dateianhänge und UUID

### ISSUE THREAD

**Issue by landzone21** [terminal42/contao-leads#62]
System: Contao 4.4.18: Wenn ich ein Fileupload aus einem Formular in einer Anfrage speichere, dann erhalte ich in der Ausgabe im Backend nur die UUID und keinen Pfad/Dateinamen. Ich habe in der Datenbanktabelle tl_lead_data nachgesehen, im Feld label wird der Pfad/Dateiname gespeichert und im Feld value die UUID.
Wie kann ich den Wert des Labels in der Backendauflistung der Anfrage ausgeben?

Im Forum erschien die Frage auch schon, aber keine Lösung dazu:
https://community.contao.org/de/showthread.php?66391-gel%C3%B6st-contao-leads-Dateianh%C3%A4nge&p=475000#post475000

**Comment by mecintosch** [comment]
Würde mich auch interessieren. Die UUID sagt einem Benutzer ja nichts. Stattdessen sollte der Link zur entsprechenden Datei angeführt sein.

**Comment by skipman** [comment]
Also ich verwende den Individuellen Export, da kann ich zum Feld auch das Format auswählen. Bei Dateianhängen wähle ich dann Datei-UUID -> Dateipfad aus.

Anpasung in library/Leads/Leads.php etwa Zeile 73:
return (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http")."://$_SERVER[HTTP_HOST]/".$filesModel->path;
Anpassung in library/Leads/DataTransformer/UuidToFilePathTransformer.php etwa Zeile 41:
return (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http")."://$_SERVER[HTTP_HOST]/".$filesModel->path;
speichert in der DB den vollständigen Pfad zur Datei (inkl. Hostnamen) und exportiert das dann auch richtig (inkl. Hostnamen)

Lediglich in den Mails bekommt man dann auf einmal sowas wie /var/www/vhosts/customer/www/domainname/files/content/Uploads_GP/IMG_5999_1024.jpg 

Das hab ich noch nicht herausgefunden, wo das var/www/vhost/usw. herkommt...

**Comment by aschempp** [comment]
das dürfte in der kommenden Version 3 behoben sein.
