### ISSUE TITLE
Export without file extensions

### ISSUE THREAD

**Issue by wb-bertram** [terminal42/contao-leads#67]
If I export a file (.xls/.xlsx/.csv), the file is get saved without the appropriate file extension.

**OSX:** filename.dsm
**Windows:** filename

I can add the file extension manually and then open the file, but this is less suitable for customers.

Does somebody has any idea to fix it?

**Info**
MySQL: mysqlnd 5.0.12-dev - 20150407
PHP-Version: 7.1.15
Contao: 3.5.24
Contao-Leads: 1.4.3

**Comment by aschempp** [comment]
You must add the file extension manually, thats how it's designed. That's especially useful if you want .txt instead of .csv or something thelike.
