### ISSUE TITLE
Leere Spalten verschieben sich nach links / Datum- und Zeit-Formatierung

### ISSUE THREAD

**Issue by mapfei** [terminal42/contao-leads#68]
Wenn ich Daten als "individueller Export" exportiere, dann verrutschen Spalten nach links, wenn entsprechende Felder (weil u.a. nicht sichtbar - [conditionalformfields](https://github.com/terminal42/contao-conditionalformfields)) nicht ausgefüllt wurden, ergo leer sind. Eine Formatierung von Spalten mit Datum und Uhrzeit bleibt korrekt erhalten.

Exportiere ich als "individueller Export mit Simple Tokens", damit die leeren Spalten ausgegeben werden (z.B. {if maiden_name!=""}##maiden_name##{endif}) und so nicht verrutschen, dann stimmt die Spaltenanordnung, jedoch die Formatierung von Datum und Uhrzeit nicht mehr. Stattdessen wird der Timestamp ausgegeben.

Contao 4.7.4
Leads 1.4.12

**Comment by aschempp** [comment]
das dürfte mit https://github.com/terminal42/contao-leads/pull/89 behoben sein.
