### ISSUE TITLE
Falsche Datumsausgabe bei Excel-Export

### ISSUE THREAD

**Issue by seibtph** [terminal42/contao-leads#70]
In der Export-Konfiguration habe ich ein Feld "Erstellungsdatum" angelegt, was nur das Datum ohne Uhrzeit ausgeben soll. Allerdings wird in der Excel-Tabelle trotzdem das Datum mit Uhrzeit ausgegeben, obwohl ich nur Datum ausgewählt habe. In dem Config-Array steht bei format auch "datim", aber es sollte ja eigentlich "date" dort stehen.

![Erstellungsdatum_Feld](https://user-images.githubusercontent.com/17127525/57138331-afa5dd80-6db2-11e9-8634-abf5f2c136f4.png)

![Erstellungsdatum_Config](https://user-images.githubusercontent.com/17127525/57138330-afa5dd80-6db2-11e9-9bdf-d7feaa3378ef.png)

**Comment by aschempp** [comment]
Das Format wird entsprechend der Systemeinstellung konvertiert. Bist du sicher dass du in den System-Einstellungen nicht Datum + Uhrzeit im Datums-Feld eingegeben hast?

**Comment by seibtph** [comment]
Im Datums-Feld in den System-Einstellungen steht auch wirklich nur das Datum ohne die Uhrzeit.

**Comment by aschempp** [comment]
Ich kann das in der neusten Version (v3) nicht reproduzieren.
