### ISSUE TITLE
New field value (slave form) is not exported on custom export

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-leads#73]
Hi,

i just added a new field "ticket" in my master form. Then i duplicated this form to use it with custom values in several pages and set them to slave forms. Submitted values for "ticket" are saved correctly - See data of a test entry:

`
ID:	575
Erhalten:	25.07.2019 21:08
Quellformular:	Events - Anmeldung - Supermoto - Veterama [ID 14]
Hauptformular:	Events - Anmeldung - Supermoto - Master [ID 11]
Sprache:	Deutsch [ID de]
eventtitle:	eventtitle [Supermoto Training im Rahmen der Veterama Hockenheim 2020]
Ticket:	Ticket [Freitag - Sonntag]
Gruppenwunsch:	Gruppenwunsch [Sportfahrer]
Vorname:	Vorname [Max]
Name:	Name [Musermann]
E-Mail::	E-Mail: [berger@mediastuff.de]
Telefonnummer:	Telefonnummer [+4917567897]
Straße:	Straße [eine Straße 54]
Postleitzahl:	Postleitzahl [80687]
Ort:	Ort [München]
`

I added the new field to my csv/xls export settings "custom export" with option "raw data". The field stays empty on custom export...even there is a saved value in contao backend listing. 

When i set export to "export all data" the values are exported. 

Maybe this is the same thing like in https://github.com/terminal42/contao-leads/issues/45 ? 
The original master form (without field ticket) already contained data before i added the new field.

Contao 4.7.7
Leads: 1.4.13

**Comment by qzminski** [comment]
I am not able to reproduce the issue. Can you send me a screenshot of your complete export configuration? Also, do you export to CSV or XLS (they are not the same)?

**Comment by Kahmoon** [comment]
I´ve send you an email.

I have exports in CSV + xlsx. Both export are exporting the value when i choose default export. With custom export it is empty...even i put the new field at the output config.

**Comment by qzminski** [comment]
@aschempp now that we know `mater_id` and `field_id` are mixed up, can you verify 7fd6e7a? It does solves the problem but I am not sure if it's the best approach.
