### ISSUE TITLE
Enhancement: Text filter options for dataset value in leads 

### ISSUE THREAD

**Issue by Kahmoon** [terminal42/contao-leads#74]
Good morning,

actually there are only a few ways to filter leads in contao backend. One of the basic contao filters for text is missing. A simple text filter for "Datensatz-Bezeichnung/data set value" would be nice.

We save leads with different event titles from the same form. The form filter does not work in this case. Also the other filters (language & member). Managing data sets is pretty difficult e.g. when you try to delete all entries of a specific event. 

Frank

**Comment by aschempp** [comment]
Implemented in 192e4f33899d7c49624d2187b2737271a57b735a
