### ISSUE TITLE
Platzhalter wird nicht ersetzt

### ISSUE THREAD

**Issue by akroii** [terminal42/contao-leads#75]
Hallo Terminal42,
ich habe ein **recht großes Eingabeformular mit vielen Eingabefeldern**. Aus irgend einem Grund werden aber zwei davon nicht ersetzt.
Formulargenerator:
![Bildschirmfoto 2019-09-20 um 09 23 38](https://user-images.githubusercontent.com/8830861/65307644-8383d100-db88-11e9-9eca-6518e484d3da.png)

Notification Center:
![Bildschirmfoto 2019-09-20 um 09 27 29](https://user-images.githubusercontent.com/8830861/65307795-e6756800-db88-11e9-8571-00ad845e6501.png)

Email:
![Bildschirmfoto 2019-09-20 um 09 29 00](https://user-images.githubusercontent.com/8830861/65307858-19b7f700-db89-11e9-9d0d-c9eefe0d88f1.png)

Habt ihr eventuell eine Idee woran das liegen könnte?

**Comment by aschempp** [comment]
Ich glaube nicht dass das etwas mit Leads zu tun hat?

**Comment by christianromeni** [comment]
Ich hab das gleiche in nem ganz Normalen Formular, ohne alles:

![image](https://user-images.githubusercontent.com/1358040/65795553-cfc3a800-e16a-11e9-9497-73bcb838c61d.png)

![image](https://user-images.githubusercontent.com/1358040/65795522-c4707c80-e16a-11e9-8b3f-deb91c606e91.png)

![image](https://user-images.githubusercontent.com/1358040/65795451-95f2a180-e16a-11e9-96d3-4fc24a0a66a2.png)

Und wenn ich in den Formular-Einstellungen den Simple Token änder, wird er in der Ansicht auch so angezeigt:

![image](https://user-images.githubusercontent.com/1358040/65795774-54aec180-e16b-11e9-824a-a5f56fc5edca.png)

Contao 4.8 mit

```
        "codefog/contao-cookiebar": "^2.1",
        "contao/calendar-bundle": "^4.8",
        "contao/comments-bundle": "^4.8",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "^4.8",
        "contao/listing-bundle": "^4.8",
        "contao/manager-bundle": "4.8.*",
        "contao/news-bundle": "^4.8",
        "contao/newsletter-bundle": "^4.8",
        "delahaye/dlh_googlemaps": "^2.4",
        "derhaeuptling/contao-seo-serp-preview": "^3.0",
        "heimrichhannot/contao-filename-sanitizer-bundle": "^1.3",
        "heimrichhannot/contao-notification_center_plus": "^1.0",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "romeniwebdesign/contao-custom-articles-bundle": "dev-master",
        "terminal42/contao-ajaxform": "^1.1",
        "terminal42/contao-changelanguage": "^3.1",
        "terminal42/contao-folderpage": "^2.0",
        "terminal42/contao-leads": "^1.4",
        "terminal42/contao-node": "^1.1",
        "terminal42/notification_center": "^1.5"
```

**Comment by rabauss** [comment]
Wir hatten schon ähnliche Probleme mit dem Notification-Center, wenn wir diesen mit der Notification-Queue betrieben haben. Dann war nämlich das Datenbank-Feld zum Speichern der Daten zu klein - vielleicht könntet ihr das mal prüfen. Tatsächlich kann ``blob`` hier ggf. zu klein sein!

**Comment by martin-hofmann-netprofit** [comment]
Hab mit Contao 4.9.1 und 4.9.2 das gleiche Problem, die Platzhalter werden nicht mehr ersetzt. Aktuell funktioniert nur der Platzhalter ##created##. 
Das Notifications-Center ist mir nicht installiert.

`        "contao/calendar-bundle": "4.9.*",
        "contao/comments-bundle": "4.9.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.9.*",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "contao/newsletter-bundle": "4.9.*",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "kmielke/calendar_extended": "^3.7",
        "madeyourday/contao-rocksolid-antispam": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "terminal42/contao-changelanguage": "^3.1",
        "terminal42/contao-leads": "^1.4" `

**Comment by aschempp** [comment]
Ich verstehs noch immer nicht. 

 1. Leads schickt keine E-Mails
 2. das Blob-Feld in tl_lead wir nicht verwendet, es ist nur als „Backup“ gedacht (enthält alle Rohdaten).

Generell ersetzt Contao die Simple Tokens nur dann, wenn auch ein entsprechender Wert vorhanden ist. Was steht denn in der Datenbank zu `##first_name##`?

**Comment by herrweiss77** [comment]
Seit einem Update von Contao 4.8 auf 4.9 und Update auf Leads Version 1.4.18 habe ich das gleiche Problem. Die Simple-Tokens werden nicht mehr ersetzt, außer ##created##.

![image](https://user-images.githubusercontent.com/44664907/86048247-7a495e00-ba50-11ea-8274-68a18745a1ae.png)

Gibt es hierfür schon eine Lösung? 

P.S. Danke für die tollen und nützlichen terminal42 Erweiterungen :-)

**Comment by richardhj** [comment]
https://github.com/terminal42/contao-leads/blob/94c36cbcd362ea7ff9512ff14e4c1b9369eacf8d/dca/tl_lead.php#L245

Hier werden die Tokens generiert. Das erklärt, warum ##created## immer geht.

Könnte man nicht auf das query verzichten und einfach $row nehmen? /cc @aschempp

**Comment by mathContao** [comment]
Contao 4.9.3 und Leads 1.4.18 funktionieren bei mir bzgl. der Platzhalter super

**Comment by aschempp** [comment]
> Könnte man nicht auf das query verzichten und einfach $row nehmen? /cc @aschempp

`$row` ist nach meinem Verständnis der Datensatz aus `tl_lead`, die Zeilen stehen aber in `tl_lead_data`. Das ersetzen der Platzhalter funktioniert bei mir problemlos. Die Tokens werden aus `tl_lead_data.name` generiert, könnt ihr mal nachschauen was dort drin steht?

**Comment by RalfGebhard** [comment]
nun mit verschiedenen Installationen Contao 4.4, 4.9, 4.10 versucht. Ich habe das gleiche Phänomen. tl_lead_data bleibt leer, obwohl tl_lead befüllt wird. Im blob von tl_lead stehen die Daten drin, aber die Detailtabelle tl_lead_data bleibt leer, daher auch keine Tokens.

**Comment by aschempp** [comment]
Dann hast du die Felder nicht korrekt als "zu speichern in Leads" konfiguriert 😉
