### ISSUE TITLE
Empfehlungen um phpoffice/phpspreadsheet erweitern

### ISSUE THREAD

**Issue by mlwebworker** [terminal42/contao-leads#80]
Vor kurzem gab es folgenden Thread im Forum https://community.contao.org/de/showthread.php?70630-Contao-Leads-mit-PhpSpreadsheet/page2&p=517110&viewfull=1#post517110 Wenn man jetzt auch phpoffice/phpspreadsheet verwenden kann, sollte das aber auch im Paket im Contao Manager als Empfehlungen verlinkt werden ( genauso wie phpoffice/phpexcel), damit eine Installation ohne manuellen Eingriff in den Composer möglich ist.

**Comment by richardhj** [comment]
Habe die Daten bei Packagist aktualiseirt

**Comment by mlwebworker** [comment]
Danke
