### ISSUE TITLE
Satzzeichen werden im Backend dekodiert

### ISSUE THREAD

**Issue by akroii** [terminal42/contao-leads#84]
Wenn man Leads im Backend mit einer Klammer `()` eingebe werden diese mit `&#40;` dargestellt.
In Contao 4.8 war dies noch kein Problem. Ab der 4.9.0 jedoch schon.

Screenshot:
![Bildschirmfoto 2020-03-10 um 10 15 21](https://user-images.githubusercontent.com/8830861/76297415-125fe380-62b8-11ea-8d7c-af7721fff437.png)

![Bildschirmfoto 2020-03-10 um 10 17 19](https://user-images.githubusercontent.com/8830861/76297590-58b54280-62b8-11ea-8b39-5d95cec835dc.png)

**Comment by aschempp** [comment]
We should probably use `decodeEntities` on these fields?

**Comment by richardhj** [comment]
See b2ce94620dcddbf9a21e301a910f69e647b80af5.
