### ISSUE TITLE
No leads-backend-module for regular contao-users

### ISSUE THREAD

**Issue by rustykowski** [terminal42/contao-leads#86]
Ich habe eine Benutzergruppe angelegt, der ich die Leads freigegeben habe. Leider erscheint das zugehörige Backend-Modul nicht bei diesen Benutzern. (Contao 4.9.2)
![image](https://user-images.githubusercontent.com/1775048/79362460-ebe03880-7f46-11ea-8d60-cf44b7af0c1a.png)

**Comment by freiwild** [comment]
Ich denke du musst in der Benutzergruppe unter Formular-Rechte die Formulare ebenfalls freigeben, deren Daten gespeichert werden sollen.

**Comment by rustykowski** [comment]
Wunderbar, das war die Lösung – danke!!
