### ISSUE TITLE
##created## wird in "Individueller Export mit Simple Tokens"  nicht ersetzt

### ISSUE THREAD

**Issue by omuellersch** [terminal42/contao-leads#87]
Im .csv-Export wird der Simple Token ##created## nicht durch das Erstellungsdatum des Eintrags ersetzt. In der csv-Datei wird ##created## ausgegeben.
Contao 4.4.48
Leads 1.4.18

**Comment by Toflar** [comment]
Maybe because it should be `##_created##`?

**Comment by freiwild** [comment]
Are you shure? Because here: https://github.com/terminal42/contao-leads "##created##" specifies and in the Leads Backend-Listing "##created##" works fine...

**Comment by Toflar** [comment]
No I'm not, was just a guess.

**Comment by Aybee** [comment]
> Im .csv-Export wird der Simple Token ##created## nicht durch das Erstellungsdatum des Eintrags ersetzt. In der csv-Datei wird ##created## ausgegeben.
> Contao 4.4.48
> Leads 1.4.18

Das gleiche bei:
Contao 4.11.2
Leads 1.4.19

**Comment by Sahel2021** [comment]
Hallo gibt es hier eine Lösung für den Export? Ich habe im Formular:
Verstecktes Feld , In Anfrage speichern ja
Feldname Date, Standard-Wert {{date}}

Datum erscheint:
in E-Mail Rohdaten
in E-Mail Anhang csv
im Backend Leads Anfragen - Formulardaten anzeigen

Konfiguration der Anfrage:  Individueller Export mit Simple Tokens
Spalte	Bezeichnung für Kopfzeile	Simple Tokens (und Insert Tags)	
1		Date						##created##

Datum erscheint nicht im Export, egal ob csv, xls, xlsx. Im Export steht immer ##created##

Kann es sein, das im Feld Simple Tokens etwas anderes stehen muss?

**Comment by aschempp** [comment]
> Maybe because it should be `##_created##`?

Pretty sure this works with any version of leads, and that should work in leads v3.

**Comment by contaoacademy** [comment]
Das Ticket ist zwar schon sehr alt, aber falls noch jemand das Problem hat. Unter Leads 1.4.33 ist das Problem mit `##created##` nach wie noch vorhanden. Ihr könnt euch also die Zeit sparen, das weiter zu testen.

Die System-Werte (created, form_id, member_id) werden nie zum Token-Array hinzugefügt.

Vermutlich müsste bei `handleTokenExports` noch was ergnäzt werden, damit die speziellen System-Werte dem Array hinzugefügt werden.
https://github.com/terminal42/contao-leads/blob/8392070cd40128a2138a9f520f132ee42b1c7d48/library/Leads/Leads.php#L429

Also Workaround kann man in Formular ein neues "verstecktes Feld" anlegen (z.B. anfragedatum).
Als Standardwert im Feld den InsertTag `{{date}}` eintragen.

Anschließend kann das Feld mit ##anfragedatum## beim Export ergänzt werden.

**Comment by aschempp** [comment]
hast du es mit `##_created##` versucht?

**Comment by contaoacademy** [comment]
> hast du es mit `##_created##` versucht?

Ja, ich habe alle Kombinationen durch: mit und ohne Unterstrich. Mit und ohne Rautezeichen. Da es aber 1.4. ist, sollten wir da nicht weiter Zeit investieren.

Außer es wäre bei der aktuellen Version auch ein Fehler, das habe ich bisher nicht getestet.
