### ISSUE TITLE
Add 'Save in leads' to filter

### ISSUE THREAD

**Issue by cliffparnitzky** [terminal42/contao-leads#88]
When defining the fields to be saved, it would be very helpful to have this filter to check the configuration.

**Comment by cliffparnitzky** [comment]
Just to mention: a simple `'filter'=>true` in the DCA is not the solution. Getting the values into the the select is the special thing.

**Comment by madmaharaja** [comment]
![image](https://user-images.githubusercontent.com/3133710/84888908-4b1e0e80-b098-11ea-8d2d-2d2e5c1d137a.png)

**Comment by aschempp** [comment]
Implemented in 39a6fe488d792c0b8e07272cb4a24360b99e4711

**Comment by cliffparnitzky** [comment]
@aschempp Awesome
