### ISSUE TITLE
it exports "txt" file extension, not "csv"

### ISSUE THREAD

**Issue by mathContao** [terminal42/contao-leads#92]
Contao 4.9.3
Leads 1.4.18

I want to export CSV files
![grafik](https://user-images.githubusercontent.com/1645099/88586959-80355d80-d055-11ea-8eed-144a102497f6.png)

But I get .txt as file extension

**Comment by fritzmg** [comment]
Contao Leads uses `\Contao\File` to send the file to the browser, which does not set a `Content-Type` response header on its own. And somewhere down the pipeline either Contao or Symfony adds the `Content-Type: text/plain` header.

`\Contao\File::sendToBrowser` is missing the following:

```php
$response->headers->set('Content-Type', $this->getMimeType());
```

**Comment by fritzmg** [comment]
If the `Content-Type` header is missing, `Response::prepare` in Symfony's `ResponseListener` will automatically add it via the `FileinfoMimeTypeGuesser` which uses [PHP Fileinfo](https://www.php.net/manual/en/book.fileinfo.php). And fileinfo will guess the mime type according to the _content_ of the file, which is just plain text in case of a CSV …

**Comment by fritzmg** [comment]
Should be fixed in the next Contao versions. See https://github.com/contao/contao/pull/2020
