### ISSUE TITLE
Details des Datensatzes anzeigen: Die wirklich wichtigen Daten werden nur grau angezeigt

### ISSUE THREAD

**Issue by mathContao** [terminal42/contao-leads#93]
Contao 4.9.4 und Contao Leads 1.4.18

In der Detailanzeige des Datensatzes werden die gespeicherten Formulardaten kaum lesbar angezeigt: in hellgrau und in eckigen Klammern.

Die Namen der Eingabefelder werden im zweiten Abschnitt doppelt (in der linken und in der rechten Spalte) angezeigt

![grafik](https://user-images.githubusercontent.com/1645099/88844382-db488b00-d1e2-11ea-9f71-77bbcf4fb5fc.png)

**Comment by mathContao** [comment]
Formulardaten der Anfrage anzeigen:

auch hier werden die eigentlich wichtigen eingegebenen Daten in grau angezeigt.

Der (technische) Feldname wird zuerst angezeigt, dann der Labelname. In grau die Nutzereingabe.
![grafik](https://user-images.githubusercontent.com/1645099/88847402-485e1f80-d1e7-11ea-9d2d-02a454cc12f5.png)

Aus meiner Sicht wäre es so sinnvoller:
Labelname: Nutzereingabe [techn. Feldname]

**Comment by mathContao** [comment]
Ich habe mir das nun mal genauer angeschaut.

Diese Liste "Details des Datensatze ID xx anzeigen" ist über das Template "be_leads_show.html5" einstellbar.
![grafik](https://user-images.githubusercontent.com/1645099/89103719-42995180-d414-11ea-95c4-de6a00ee0284.png)

in https://github.com/terminal42/contao-leads/blob/master/library/Leads/Leads.php wird das value-Feld formatiert. Dort wird (leider) das HTML und CSS fixiert.
![grafik](https://user-images.githubusercontent.com/1645099/89103748-6b214b80-d414-11ea-8131-6cb102e11e17.png)

Schöner wäre, wenn $strLabel und $strValue jeweils einzeln im Template geführt werden.

**Comment by aschempp** [comment]
Behoben in 9805cbd9ead45caa1f62517fe3f51585194b8d09

**Comment by mathContao** [comment]
Vielen Dank. Sieht jetzt super aus :)
