### ISSUE TITLE
Gruppenrechte: Einstellbarkeit der Aktionen

### ISSUE THREAD

**Issue by math-GH** [terminal42/contao-leads#94]
Contao 4.9.4 und Contao Leads 1.4.18

Es wäre sehr hilfreich, wenn über die Benutzergruppen die Datensation-Aktionen (Löschen, Datensätze anzeigen, Benachrichtigung versenden + Datei-Downloads) gesteuert werden können.
![grafik](https://user-images.githubusercontent.com/1645099/88848397-b6efad00-d1e8-11ea-9419-1e61287dcd67.png)

Aktuell kann ich keine Rechte auf diese Liste vergeben, da das Löschen und Versenden der Benachrichtigungen damit nicht für ausgewähle Benutzergruppen verhindert werden kann.

**Comment by aschempp** [comment]
Upcoming leads v3 now has permissions for editing and deleting leads.
