### ISSUE TITLE
CSV-Export: Anführungszeichen nur, wenn Leerzeichen vorhanden ist

### ISSUE THREAD

**Issue by math-GH** [terminal42/contao-leads#97]
Contao 4.9.4
Leads 1.4.18

CSV-Export
Wenn der Ausgabestring ein Leerzeichen enthält, dann wird der String durch Anführungszeichen gewrappt.
Ohne Leerzeichen = ohne Anführungszeichen.

![grafik](https://user-images.githubusercontent.com/1645099/89225221-27783e80-d5da-11ea-9850-922fbcac8e08.png)

Das führt beim Öffnen in der Tabellenkalkulation zu folgenden Effekten:
- Telefonnummern werden als Zahlen verstanden: das Pluszeichen verschwindet oder die führende Null wird weggelassen.
- Postleitzahlen: führende Null wird weggelassen (somit wird aus einer 5stelligen PLZ eine 4stellige PLZ)

Vielleicht lässt sich das in den Export-Einstellungen festlegen
![grafik](https://user-images.githubusercontent.com/1645099/89225707-f2202080-d5da-11ea-94b4-55d782f0e5b1.png)
(nur den Wert = wie gehabt; Zeichenkette = immer Anführungszeichen)

**Comment by aschempp** [comment]
Ich vermute das ist eher ein Problem des "Lese-Programms", also vermutlich Excel? In der neusten Version haben wir einen Excel-kompatiblen Export drin, damit dürfte das behoben sein.
